//
//  TShirtCanvas.swift
//  Blagaprint
//
//  Created by Ivan Magda on 07.02.16.
//  Copyright (c) 2016 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class TShirtCanvas : NSObject {

    //// Drawing Methods

    public class func drawFront(frame frame: CGRect = CGRectMake(0, 0, 320, 320), tshirtColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        var tshirtColorRedComponent: CGFloat = 1,
            tshirtColorGreenComponent: CGFloat = 1,
            tshirtColorBlueComponent: CGFloat = 1
        tshirtColor.getRed(&tshirtColorRedComponent, green: &tshirtColorGreenComponent, blue: &tshirtColorBlueComponent, alpha: nil)

        let strokeColor = UIColor(red: (tshirtColorRedComponent * 0), green: (tshirtColorGreenComponent * 0), blue: (tshirtColorBlueComponent * 0), alpha: (CGColorGetAlpha(tshirtColor.CGColor) * 0 + 1))

        //// Gradient Declarations
        let gradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [UIColor.lightGrayColor().CGColor, UIColor.lightGrayColor().blendedColorWithFraction(0.5, ofColor: UIColor.whiteColor()).CGColor, UIColor.whiteColor().CGColor], [0, 0.12, 1])!

        //// Shadow Declarations
        let neckInnerShadow = NSShadow()
        neckInnerShadow.shadowColor = UIColor.lightGrayColor()
        neckInnerShadow.shadowOffset = CGSizeMake(0.1, -3.1)
        neckInnerShadow.shadowBlurRadius = 2
        let tShirtOuterShadow = NSShadow()
        tShirtOuterShadow.shadowColor = UIColor.grayColor()
        tShirtOuterShadow.shadowOffset = CGSizeMake(4.1, 3.1)
        tShirtOuterShadow.shadowBlurRadius = 8

        //// T-ShirtGroup
        //// T-ShirtBezier Drawing
        let tShirtBezierPath = UIBezierPath()
        tShirtBezierPath.moveToPoint(CGPointMake(frame.minX + 194.02, frame.minY + 35))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 161.5, frame.minY + 38.44), controlPoint1: CGPointMake(frame.minX + 194.02, frame.minY + 35), controlPoint2: CGPointMake(frame.minX + 178.34, frame.minY + 38.44))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 126.65, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 144.66, frame.minY + 38.44), controlPoint2: CGPointMake(frame.minX + 126.65, frame.minY + 35))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 68.58, frame.minY + 47.27), controlPoint1: CGPointMake(frame.minX + 126.65, frame.minY + 35), controlPoint2: CGPointMake(frame.minX + 80.19, frame.minY + 42.36))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 45.35, frame.minY + 71.82), controlPoint1: CGPointMake(frame.minX + 56.96, frame.minY + 52.18), controlPoint2: CGPointMake(frame.minX + 62.77, frame.minY + 56.48))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 20.88, frame.minY + 96.55), controlPoint1: CGPointMake(frame.minX + 36.41, frame.minY + 79.69), controlPoint2: CGPointMake(frame.minX + 27.46, frame.minY + 89.18))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 10.5, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 14.63, frame.minY + 103.55), controlPoint2: CGPointMake(frame.minX + 10.21, frame.minY + 102.57))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 22.03, frame.minY + 120.82), controlPoint1: CGPointMake(frame.minX + 10.79, frame.minY + 114.7), controlPoint2: CGPointMake(frame.minX + 22.03, frame.minY + 120.82))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 33.73, frame.minY + 133.18))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 45.35, frame.minY + 141.77), controlPoint1: CGPointMake(frame.minX + 33.73, frame.minY + 133.18), controlPoint2: CGPointMake(frame.minX + 39.54, frame.minY + 141.77))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 52.32, frame.minY + 138.09), controlPoint1: CGPointMake(frame.minX + 51.16, frame.minY + 141.77), controlPoint2: CGPointMake(frame.minX + 52.32, frame.minY + 138.09))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 54.13, frame.minY + 134.94), controlPoint1: CGPointMake(frame.minX + 52.32, frame.minY + 138.09), controlPoint2: CGPointMake(frame.minX + 52.63, frame.minY + 136.53))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 58.33, frame.minY + 131.73), controlPoint1: CGPointMake(frame.minX + 55.64, frame.minY + 133.36), controlPoint2: CGPointMake(frame.minX + 58.33, frame.minY + 131.73))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 68.14, frame.minY + 121.37))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 80.19, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 68.14, frame.minY + 121.37), controlPoint2: CGPointMake(frame.minX + 78.34, frame.minY + 108.45))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 80.19, frame.minY + 122.14), controlPoint1: CGPointMake(frame.minX + 82.05, frame.minY + 108.83), controlPoint2: CGPointMake(frame.minX + 80.19, frame.minY + 122.14))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 80.19, frame.minY + 293.95))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 81.36, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 80.19, frame.minY + 293.95), controlPoint2: CGPointMake(frame.minX + 75.55, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 84.84, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 87.16, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 84.84, frame.minY + 305))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 236, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 241.65, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 236, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 235.84, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 293.95), controlPoint1: CGPointMake(frame.minX + 247.45, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 242.81, frame.minY + 293.95))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 122.14))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 242.81, frame.minY + 122.14), controlPoint2: CGPointMake(frame.minX + 241.2, frame.minY + 108.96))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 253.88, frame.minY + 120.84), controlPoint1: CGPointMake(frame.minX + 244.41, frame.minY + 108.31), controlPoint2: CGPointMake(frame.minX + 253.88, frame.minY + 120.84))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 262.45, frame.minY + 130.3))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 267, frame.minY + 134.03), controlPoint1: CGPointMake(frame.minX + 262.45, frame.minY + 130.3), controlPoint2: CGPointMake(frame.minX + 265.24, frame.minY + 132.08))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 269.52, frame.minY + 138.09), controlPoint1: CGPointMake(frame.minX + 268.77, frame.minY + 135.98), controlPoint2: CGPointMake(frame.minX + 269.52, frame.minY + 138.09))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 277.65, frame.minY + 143), controlPoint1: CGPointMake(frame.minX + 269.52, frame.minY + 138.09), controlPoint2: CGPointMake(frame.minX + 272.16, frame.minY + 142.82))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 288.31, frame.minY + 134.2), controlPoint1: CGPointMake(frame.minX + 283.15, frame.minY + 143.18), controlPoint2: CGPointMake(frame.minX + 288.31, frame.minY + 134.2))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 301.67, frame.minY + 120.08))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 312.5, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 301.67, frame.minY + 120.08), controlPoint2: CGPointMake(frame.minX + 312.55, frame.minY + 114.7))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 301.46, frame.minY + 95.82), controlPoint1: CGPointMake(frame.minX + 312.45, frame.minY + 102.57), controlPoint2: CGPointMake(frame.minX + 308.08, frame.minY + 103.19))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 277.65, frame.minY + 71.82), controlPoint1: CGPointMake(frame.minX + 294.95, frame.minY + 88.56), controlPoint2: CGPointMake(frame.minX + 286.3, frame.minY + 79.43))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 254.42, frame.minY + 47.27), controlPoint1: CGPointMake(frame.minX + 260.23, frame.minY + 56.48), controlPoint2: CGPointMake(frame.minX + 266.04, frame.minY + 53.41))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 194.02, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 242.81, frame.minY + 41.14), controlPoint2: CGPointMake(frame.minX + 194.02, frame.minY + 35))
        tShirtBezierPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, tShirtOuterShadow.shadowOffset, tShirtOuterShadow.shadowBlurRadius, (tShirtOuterShadow.shadowColor as! UIColor).CGColor)
        tshirtColor.setFill()
        tShirtBezierPath.fill()
        CGContextRestoreGState(context)

        strokeColor.setStroke()
        tShirtBezierPath.lineWidth = 2
        tShirtBezierPath.stroke()


        if (imageVisible) {
            //// ImageRectangle Drawing
            let imageRectangleRect = CGRectMake(frame.minX + 100, frame.minY + 100, 120, 170)
            let imageRectanglePath = UIBezierPath(rect: imageRectangleRect)
            CGContextSaveGState(context)
            imageRectanglePath.addClip()
            image.drawInRect(CGRectMake(floor(imageRectangleRect.minX + 0.5), floor(imageRectangleRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
        }




        //// NeckGroup
        //// Neck Drawing
        let neckPath = UIBezierPath()
        neckPath.moveToPoint(CGPointMake(frame.minX + 191.44, frame.minY + 43.39))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 188.7, frame.minY + 63.01), controlPoint1: CGPointMake(frame.minX + 200.95, frame.minY + 45.56), controlPoint2: CGPointMake(frame.minX + 191.08, frame.minY + 60.87))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 160.03, frame.minY + 72.5), controlPoint1: CGPointMake(frame.minX + 185.16, frame.minY + 66.17), controlPoint2: CGPointMake(frame.minX + 177.38, frame.minY + 72.5))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 131.37, frame.minY + 63.01), controlPoint1: CGPointMake(frame.minX + 142.69, frame.minY + 72.5), controlPoint2: CGPointMake(frame.minX + 133.34, frame.minY + 66.17))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 128.62, frame.minY + 43.39), controlPoint1: CGPointMake(frame.minX + 130.03, frame.minY + 60.84), controlPoint2: CGPointMake(frame.minX + 120.77, frame.minY + 46.55))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 159.64, frame.minY + 46.55), controlPoint1: CGPointMake(frame.minX + 136.48, frame.minY + 40.22), controlPoint2: CGPointMake(frame.minX + 154.14, frame.minY + 46.55))
        neckPath.addCurveToPoint(CGPointMake(frame.minX + 191.44, frame.minY + 43.39), controlPoint1: CGPointMake(frame.minX + 165.27, frame.minY + 46.55), controlPoint2: CGPointMake(frame.minX + 186.87, frame.minY + 42.34))
        neckPath.closePath()
        UIColor.whiteColor().setFill()
        neckPath.fill()
        strokeColor.setStroke()
        neckPath.lineWidth = 1
        neckPath.stroke()


        //// NeckInner Drawing
        let neckInnerPath = UIBezierPath()
        neckInnerPath.moveToPoint(CGPointMake(frame.minX + 190.12, frame.minY + 47.74))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 187.91, frame.minY + 63.67), controlPoint1: CGPointMake(frame.minX + 199.22, frame.minY + 49.55), controlPoint2: CGPointMake(frame.minX + 190.19, frame.minY + 61.89))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 160.05, frame.minY + 72), controlPoint1: CGPointMake(frame.minX + 184.53, frame.minY + 66.3), controlPoint2: CGPointMake(frame.minX + 176.66, frame.minY + 72))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 132.62, frame.minY + 64.09), controlPoint1: CGPointMake(frame.minX + 143.45, frame.minY + 72), controlPoint2: CGPointMake(frame.minX + 134.5, frame.minY + 66.73))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 129.99, frame.minY + 47.74), controlPoint1: CGPointMake(frame.minX + 131.34, frame.minY + 62.29), controlPoint2: CGPointMake(frame.minX + 122.47, frame.minY + 50.38))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 159.68, frame.minY + 50.38), controlPoint1: CGPointMake(frame.minX + 137.51, frame.minY + 45.1), controlPoint2: CGPointMake(frame.minX + 154.41, frame.minY + 50.38))
        neckInnerPath.addCurveToPoint(CGPointMake(frame.minX + 190.12, frame.minY + 47.74), controlPoint1: CGPointMake(frame.minX + 165.07, frame.minY + 50.38), controlPoint2: CGPointMake(frame.minX + 185.74, frame.minY + 46.87))
        neckInnerPath.closePath()
        CGContextSaveGState(context)
        neckInnerPath.addClip()
        let neckInnerBounds = CGPathGetPathBoundingBox(neckInnerPath.CGPath)
        CGContextDrawLinearGradient(context, gradient,
            CGPointMake(neckInnerBounds.midX, neckInnerBounds.minY),
            CGPointMake(neckInnerBounds.midX, neckInnerBounds.maxY),
            CGGradientDrawingOptions())
        CGContextRestoreGState(context)

        ////// NeckInner Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, neckInnerPath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha((neckInnerShadow.shadowColor as! UIColor).CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let neckInnerOpaqueShadow = (neckInnerShadow.shadowColor as! UIColor).colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, neckInnerShadow.shadowOffset, neckInnerShadow.shadowBlurRadius, neckInnerOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, .SourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        neckInnerOpaqueShadow.setFill()
        neckInnerPath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        UIColor.blackColor().setStroke()
        neckInnerPath.lineWidth = 0.5
        neckInnerPath.stroke()
    }

    public class func drawBack(frame frame: CGRect = CGRectMake(0, 0, 320, 320), tshirtColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        var tshirtColorRedComponent: CGFloat = 1,
            tshirtColorGreenComponent: CGFloat = 1,
            tshirtColorBlueComponent: CGFloat = 1
        tshirtColor.getRed(&tshirtColorRedComponent, green: &tshirtColorGreenComponent, blue: &tshirtColorBlueComponent, alpha: nil)

        let strokeColor = UIColor(red: (tshirtColorRedComponent * 0), green: (tshirtColorGreenComponent * 0), blue: (tshirtColorBlueComponent * 0), alpha: (CGColorGetAlpha(tshirtColor.CGColor) * 0 + 1))

        //// Shadow Declarations
        let tShirtOuterShadow = NSShadow()
        tShirtOuterShadow.shadowColor = UIColor.grayColor()
        tShirtOuterShadow.shadowOffset = CGSizeMake(4.1, 3.1)
        tShirtOuterShadow.shadowBlurRadius = 8

        //// T-ShirtBezier Drawing
        let tShirtBezierPath = UIBezierPath()
        tShirtBezierPath.moveToPoint(CGPointMake(frame.minX + 194.03, frame.minY + 35))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 161.5, frame.minY + 37.41), controlPoint1: CGPointMake(frame.minX + 194.03, frame.minY + 35), controlPoint2: CGPointMake(frame.minX + 178.34, frame.minY + 37.41))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 126.66, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 144.66, frame.minY + 37.41), controlPoint2: CGPointMake(frame.minX + 126.66, frame.minY + 35))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 68.58, frame.minY + 47.27), controlPoint1: CGPointMake(frame.minX + 126.66, frame.minY + 35), controlPoint2: CGPointMake(frame.minX + 80.2, frame.minY + 42.36))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 45.35, frame.minY + 71.82), controlPoint1: CGPointMake(frame.minX + 56.96, frame.minY + 52.18), controlPoint2: CGPointMake(frame.minX + 62.77, frame.minY + 56.48))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 20.88, frame.minY + 96.55), controlPoint1: CGPointMake(frame.minX + 36.41, frame.minY + 79.69), controlPoint2: CGPointMake(frame.minX + 27.47, frame.minY + 89.18))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 10.5, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 14.63, frame.minY + 103.55), controlPoint2: CGPointMake(frame.minX + 10.21, frame.minY + 102.57))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 22.03, frame.minY + 120.82), controlPoint1: CGPointMake(frame.minX + 10.79, frame.minY + 114.7), controlPoint2: CGPointMake(frame.minX + 22.03, frame.minY + 120.82))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 33.73, frame.minY + 133.18))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 45.35, frame.minY + 141.77), controlPoint1: CGPointMake(frame.minX + 33.73, frame.minY + 133.18), controlPoint2: CGPointMake(frame.minX + 39.54, frame.minY + 141.77))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 52.32, frame.minY + 138.09), controlPoint1: CGPointMake(frame.minX + 51.16, frame.minY + 141.77), controlPoint2: CGPointMake(frame.minX + 52.32, frame.minY + 138.09))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 54.13, frame.minY + 134.94), controlPoint1: CGPointMake(frame.minX + 52.32, frame.minY + 138.09), controlPoint2: CGPointMake(frame.minX + 52.63, frame.minY + 136.53))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 58.34, frame.minY + 131.73), controlPoint1: CGPointMake(frame.minX + 55.64, frame.minY + 133.36), controlPoint2: CGPointMake(frame.minX + 58.34, frame.minY + 131.73))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 68.14, frame.minY + 121.37))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 68.14, frame.minY + 121.37), controlPoint2: CGPointMake(frame.minX + 78.34, frame.minY + 108.45))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 122.14), controlPoint1: CGPointMake(frame.minX + 82.05, frame.minY + 108.83), controlPoint2: CGPointMake(frame.minX + 80.2, frame.minY + 122.14))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 293.95))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 81.36, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 80.2, frame.minY + 293.95), controlPoint2: CGPointMake(frame.minX + 75.55, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 84.84, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 87.16, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 84.84, frame.minY + 305))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 236, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 241.65, frame.minY + 305), controlPoint1: CGPointMake(frame.minX + 236, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 235.84, frame.minY + 305))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 293.95), controlPoint1: CGPointMake(frame.minX + 247.46, frame.minY + 305), controlPoint2: CGPointMake(frame.minX + 242.81, frame.minY + 293.95))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 122.14))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 242.81, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 242.81, frame.minY + 122.14), controlPoint2: CGPointMake(frame.minX + 241.2, frame.minY + 108.96))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 253.88, frame.minY + 120.84), controlPoint1: CGPointMake(frame.minX + 244.42, frame.minY + 108.31), controlPoint2: CGPointMake(frame.minX + 253.88, frame.minY + 120.84))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 262.45, frame.minY + 130.3))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 267.01, frame.minY + 134.03), controlPoint1: CGPointMake(frame.minX + 262.45, frame.minY + 130.3), controlPoint2: CGPointMake(frame.minX + 265.24, frame.minY + 132.08))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 269.52, frame.minY + 138.09), controlPoint1: CGPointMake(frame.minX + 268.77, frame.minY + 135.98), controlPoint2: CGPointMake(frame.minX + 269.52, frame.minY + 138.09))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 277.66, frame.minY + 143), controlPoint1: CGPointMake(frame.minX + 269.52, frame.minY + 138.09), controlPoint2: CGPointMake(frame.minX + 272.16, frame.minY + 142.82))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 288.31, frame.minY + 134.2), controlPoint1: CGPointMake(frame.minX + 283.15, frame.minY + 143.18), controlPoint2: CGPointMake(frame.minX + 288.31, frame.minY + 134.2))
        tShirtBezierPath.addLineToPoint(CGPointMake(frame.minX + 301.67, frame.minY + 120.08))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 312.5, frame.minY + 108.64), controlPoint1: CGPointMake(frame.minX + 301.67, frame.minY + 120.08), controlPoint2: CGPointMake(frame.minX + 312.55, frame.minY + 114.7))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 301.47, frame.minY + 95.82), controlPoint1: CGPointMake(frame.minX + 312.45, frame.minY + 102.57), controlPoint2: CGPointMake(frame.minX + 308.08, frame.minY + 103.19))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 277.66, frame.minY + 71.82), controlPoint1: CGPointMake(frame.minX + 294.95, frame.minY + 88.56), controlPoint2: CGPointMake(frame.minX + 286.3, frame.minY + 79.43))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 254.42, frame.minY + 47.27), controlPoint1: CGPointMake(frame.minX + 260.23, frame.minY + 56.48), controlPoint2: CGPointMake(frame.minX + 266.04, frame.minY + 53.41))
        tShirtBezierPath.addCurveToPoint(CGPointMake(frame.minX + 194.03, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 242.81, frame.minY + 41.14), controlPoint2: CGPointMake(frame.minX + 194.03, frame.minY + 35))
        tShirtBezierPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, tShirtOuterShadow.shadowOffset, tShirtOuterShadow.shadowBlurRadius, (tShirtOuterShadow.shadowColor as! UIColor).CGColor)
        tshirtColor.setFill()
        tShirtBezierPath.fill()
        CGContextRestoreGState(context)

        strokeColor.setStroke()
        tShirtBezierPath.lineWidth = 2
        tShirtBezierPath.stroke()


        if (imageVisible) {
            //// ImageRectangle Drawing
            let imageRectangleRect = CGRectMake(frame.minX + 100, frame.minY + 100, 120, 170)
            let imageRectanglePath = UIBezierPath(rect: imageRectangleRect)
            CGContextSaveGState(context)
            imageRectanglePath.addClip()
            image.drawInRect(CGRectMake(floor(imageRectangleRect.minX + 0.5), floor(imageRectangleRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
        }
    }

    //// Generated Images

    public class func imageOfFront(frame frame: CGRect = CGRectMake(0, 0, 320, 320), tshirtColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            TShirtCanvas.drawFront(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), tshirtColor: tshirtColor, image: image, imageVisible: imageVisible)

        let imageOfFront = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfFront
    }

    public class func imageOfBack(frame frame: CGRect = CGRectMake(0, 0, 320, 320), tshirtColor: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            TShirtCanvas.drawBack(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), tshirtColor: tshirtColor, image: image, imageVisible: imageVisible)

        let imageOfBack = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfBack
    }

}



extension UIColor {
    func blendedColorWithFraction(fraction: CGFloat, ofColor color: UIColor) -> UIColor {
        var r1: CGFloat = 1.0, g1: CGFloat = 1.0, b1: CGFloat = 1.0, a1: CGFloat = 1.0
        var r2: CGFloat = 1.0, g2: CGFloat = 1.0, b2: CGFloat = 1.0, a2: CGFloat = 1.0

        self.getRed(&r1, green: &g1, blue: &b1, alpha: &a1)
        color.getRed(&r2, green: &g2, blue: &b2, alpha: &a2)

        return UIColor(red: r1 * (1 - fraction) + r2 * fraction,
            green: g1 * (1 - fraction) + g2 * fraction,
            blue: b1 * (1 - fraction) + b2 * fraction,
            alpha: a1 * (1 - fraction) + a2 * fraction);
    }
}
