//
//  SH15_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 27.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH15_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH15(frame frame: CGRect = CGRectMake(41, 22, 817, 461), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.blackColor()
        outerShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        outerShadow.shadowBlurRadius = 10

        //// Image Declarations
        let sh15_placeholderImage = UIImage(named: "sh15_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 817, 461)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sh15_placeholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sh15_placeholderImage.size.width, sh15_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// PickedImageRectangle Drawing
        let pickedImageRectangleRect = CGRectMake(frame.minX + 38.98, frame.minY + 43.75, 751, 339)
        let pickedImageRectanglePath = UIBezierPath()
        pickedImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 39, frame.minY + 100.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 47, frame.minY + 113.99), controlPoint1: CGPointMake(frame.minX + 39.04, frame.minY + 104.86), controlPoint2: CGPointMake(frame.minX + 47, frame.minY + 99.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 43, frame.minY + 148.98), controlPoint1: CGPointMake(frame.minX + 47, frame.minY + 122.63), controlPoint2: CGPointMake(frame.minX + 38.97, frame.minY + 145.78))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 164.98), controlPoint1: CGPointMake(frame.minX + 45.91, frame.minY + 151.3), controlPoint2: CGPointMake(frame.minX + 53.2, frame.minY + 158.14))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 179.98), controlPoint1: CGPointMake(frame.minX + 56.67, frame.minY + 171.36), controlPoint2: CGPointMake(frame.minX + 55.65, frame.minY + 176.48))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 54, frame.minY + 215.97), controlPoint1: CGPointMake(frame.minX + 53.42, frame.minY + 188.42), controlPoint2: CGPointMake(frame.minX + 54.53, frame.minY + 208.77))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 266.96), controlPoint1: CGPointMake(frame.minX + 52.33, frame.minY + 238.66), controlPoint2: CGPointMake(frame.minX + 55.26, frame.minY + 256.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 315.96), controlPoint1: CGPointMake(frame.minX + 54.52, frame.minY + 286), controlPoint2: CGPointMake(frame.minX + 55.48, frame.minY + 302.26))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61, frame.minY + 335.95), controlPoint1: CGPointMake(frame.minX + 54.74, frame.minY + 323.29), controlPoint2: CGPointMake(frame.minX + 62.75, frame.minY + 330.45))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 51, frame.minY + 358.95), controlPoint1: CGPointMake(frame.minX + 54, frame.minY + 357.95), controlPoint2: CGPointMake(frame.minX + 51, frame.minY + 358.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61, frame.minY + 364.95), controlPoint1: CGPointMake(frame.minX + 51, frame.minY + 358.95), controlPoint2: CGPointMake(frame.minX + 49, frame.minY + 362.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 94, frame.minY + 368.95), controlPoint1: CGPointMake(frame.minX + 66.44, frame.minY + 365.85), controlPoint2: CGPointMake(frame.minX + 80.46, frame.minY + 365.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 126, frame.minY + 381.94), controlPoint1: CGPointMake(frame.minX + 110.31, frame.minY + 373.34), controlPoint2: CGPointMake(frame.minX + 126, frame.minY + 381.94))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 160, frame.minY + 382.2))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 187, frame.minY + 379.94), controlPoint1: CGPointMake(frame.minX + 160, frame.minY + 382.2), controlPoint2: CGPointMake(frame.minX + 173.75, frame.minY + 377.25))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 206, frame.minY + 381.95), controlPoint1: CGPointMake(frame.minX + 193.73, frame.minY + 381.32), controlPoint2: CGPointMake(frame.minX + 200.01, frame.minY + 384.12))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 217, frame.minY + 376.95), controlPoint1: CGPointMake(frame.minX + 209.9, frame.minY + 380.53), controlPoint2: CGPointMake(frame.minX + 213.93, frame.minY + 376.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 275.99, frame.minY + 381.95), controlPoint1: CGPointMake(frame.minX + 220.19, frame.minY + 376.95), controlPoint2: CGPointMake(frame.minX + 242.21, frame.minY + 382.06))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 315.99, frame.minY + 377.95), controlPoint1: CGPointMake(frame.minX + 287.65, frame.minY + 381.91), controlPoint2: CGPointMake(frame.minX + 301.85, frame.minY + 378.07))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 364.99, frame.minY + 381.95), controlPoint1: CGPointMake(frame.minX + 328.26, frame.minY + 377.84), controlPoint2: CGPointMake(frame.minX + 351.27, frame.minY + 382.04))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 394.99, frame.minY + 364.95), controlPoint1: CGPointMake(frame.minX + 382.52, frame.minY + 381.82), controlPoint2: CGPointMake(frame.minX + 375.81, frame.minY + 365.18))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 457.99, frame.minY + 368.95), controlPoint1: CGPointMake(frame.minX + 415.31, frame.minY + 364.7), controlPoint2: CGPointMake(frame.minX + 436.37, frame.minY + 368.9))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 498.99, frame.minY + 366.95), controlPoint1: CGPointMake(frame.minX + 469.87, frame.minY + 368.97), controlPoint2: CGPointMake(frame.minX + 486.96, frame.minY + 366.89))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 534.99, frame.minY + 372.95), controlPoint1: CGPointMake(frame.minX + 509.81, frame.minY + 366.99), controlPoint2: CGPointMake(frame.minX + 524.24, frame.minY + 372.84))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 559.99, frame.minY + 364.95), controlPoint1: CGPointMake(frame.minX + 546.02, frame.minY + 373.06), controlPoint2: CGPointMake(frame.minX + 549.21, frame.minY + 364.88))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 622.99, frame.minY + 374.95), controlPoint1: CGPointMake(frame.minX + 574.28, frame.minY + 365.03), controlPoint2: CGPointMake(frame.minX + 622.99, frame.minY + 374.95))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 657, frame.minY + 375.19))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 674.98, frame.minY + 371.95), controlPoint1: CGPointMake(frame.minX + 657, frame.minY + 375.19), controlPoint2: CGPointMake(frame.minX + 670.68, frame.minY + 371.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 757.98, frame.minY + 371.95), controlPoint1: CGPointMake(frame.minX + 708.22, frame.minY + 371.91), controlPoint2: CGPointMake(frame.minX + 746.97, frame.minY + 374.7))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 779.98, frame.minY + 358.95), controlPoint1: CGPointMake(frame.minX + 769, frame.minY + 369.19), controlPoint2: CGPointMake(frame.minX + 774.34, frame.minY + 370.85))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 780.55, frame.minY + 324.33), controlPoint1: CGPointMake(frame.minX + 785.62, frame.minY + 347.04), controlPoint2: CGPointMake(frame.minX + 790.55, frame.minY + 331.58))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 779.98, frame.minY + 266.96), controlPoint1: CGPointMake(frame.minX + 770.55, frame.minY + 317.08), controlPoint2: CGPointMake(frame.minX + 772.98, frame.minY + 285.21))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 781.98, frame.minY + 223.97), controlPoint1: CGPointMake(frame.minX + 786.98, frame.minY + 248.72), controlPoint2: CGPointMake(frame.minX + 779.09, frame.minY + 232.64))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 789.98, frame.minY + 183.98), controlPoint1: CGPointMake(frame.minX + 784.98, frame.minY + 214.97), controlPoint2: CGPointMake(frame.minX + 789.96, frame.minY + 194.25))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 756.98, frame.minY + 128.99), controlPoint1: CGPointMake(frame.minX + 790, frame.minY + 175.08), controlPoint2: CGPointMake(frame.minX + 759, frame.minY + 159.07))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 767.98, frame.minY + 100.99), controlPoint1: CGPointMake(frame.minX + 756.45, frame.minY + 121.05), controlPoint2: CGPointMake(frame.minX + 756.59, frame.minY + 108.4))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 786.41, frame.minY + 90.11), controlPoint1: CGPointMake(frame.minX + 776.8, frame.minY + 95.26), controlPoint2: CGPointMake(frame.minX + 785.65, frame.minY + 95.37))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 767.98, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 789.36, frame.minY + 69.48), controlPoint2: CGPointMake(frame.minX + 767.98, frame.minY + 62))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 702.98, frame.minY + 51), controlPoint1: CGPointMake(frame.minX + 767.98, frame.minY + 62), controlPoint2: CGPointMake(frame.minX + 735.21, frame.minY + 51.59))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 659.99, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 692.01, frame.minY + 50.8), controlPoint2: CGPointMake(frame.minX + 673.6, frame.minY + 56.16))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 621.99, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 656.57, frame.minY + 55.96), controlPoint2: CGPointMake(frame.minX + 641.33, frame.minY + 60.37))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 574.74, frame.minY + 50.29), controlPoint1: CGPointMake(frame.minX + 607.77, frame.minY + 57.99), controlPoint2: CGPointMake(frame.minX + 591.13, frame.minY + 52.23))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 521.36, frame.minY + 43.87), controlPoint1: CGPointMake(frame.minX + 555.03, frame.minY + 47.97), controlPoint2: CGPointMake(frame.minX + 535.69, frame.minY + 44.62))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 498.99, frame.minY + 45), controlPoint1: CGPointMake(frame.minX + 509.95, frame.minY + 43.27), controlPoint2: CGPointMake(frame.minX + 501.72, frame.minY + 45.05))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 473.99, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 494.11, frame.minY + 44.92), controlPoint2: CGPointMake(frame.minX + 485.03, frame.minY + 55.04))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 416.99, frame.minY + 51), controlPoint1: CGPointMake(frame.minX + 453.08, frame.minY + 57.81), controlPoint2: CGPointMake(frame.minX + 426.44, frame.minY + 51.08))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 399.99, frame.minY + 57), controlPoint1: CGPointMake(frame.minX + 407.19, frame.minY + 50.91), controlPoint2: CGPointMake(frame.minX + 412.69, frame.minY + 54.05))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 363.99, frame.minY + 57), controlPoint1: CGPointMake(frame.minX + 395.86, frame.minY + 57.96), controlPoint2: CGPointMake(frame.minX + 374.08, frame.minY + 56.19))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 343.99, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 350.91, frame.minY + 58.04), controlPoint2: CGPointMake(frame.minX + 349.09, frame.minY + 61.58))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 314.99, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 331.94, frame.minY + 63), controlPoint2: CGPointMake(frame.minX + 325.72, frame.minY + 68.82))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 281.99, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 301.32, frame.minY + 66.95), controlPoint2: CGPointMake(frame.minX + 293.55, frame.minY + 59.03))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 263.99, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 279.05, frame.minY + 58.99), controlPoint2: CGPointMake(frame.minX + 267.63, frame.minY + 61.65))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 252.99, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 260.06, frame.minY + 62.37), controlPoint2: CGPointMake(frame.minX + 257.42, frame.minY + 66.87))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 206, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 233.97, frame.minY + 72.83), controlPoint2: CGPointMake(frame.minX + 218.25, frame.minY + 68.17))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 186, frame.minY + 74), controlPoint1: CGPointMake(frame.minX + 201.86, frame.minY + 67.94), controlPoint2: CGPointMake(frame.minX + 194.67, frame.minY + 74.1))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 142, frame.minY + 67), controlPoint1: CGPointMake(frame.minX + 169.54, frame.minY + 73.8), controlPoint2: CGPointMake(frame.minX + 148.91, frame.minY + 67.28))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 94, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 118.99, frame.minY + 66.06), controlPoint2: CGPointMake(frame.minX + 107.43, frame.minY + 60.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 43, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 56.6, frame.minY + 54.67), controlPoint2: CGPointMake(frame.minX + 45.16, frame.minY + 53.53))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 39, frame.minY + 100.99), controlPoint1: CGPointMake(frame.minX + 41.4, frame.minY + 57.83), controlPoint2: CGPointMake(frame.minX + 38.74, frame.minY + 74.99))
        pickedImageRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        pickedImageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(pickedImageRectangleRect.minX + 0.5), floor(pickedImageRectangleRect.minY + 0.75 + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH15(frame frame: CGRect = CGRectMake(41, 22, 817, 461), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH15_PhotoFrame.drawSH15(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH15 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH15
    }

}
