//
//  SH38_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 27.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH38_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH38(frame frame: CGRect = CGRectMake(89, 54, 462, 356), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.blackColor()
        outerShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        outerShadow.shadowBlurRadius = 10

        //// Image Declarations
        let sh38_placeholderImage = UIImage(named: "sh38_placeholderImage.jpg")!

        //// Placeholder Drawing
        let placeholderRect = CGRectMake(frame.minX, frame.minY, 462, 356)
        let placeholderPath = UIBezierPath(rect: placeholderRect)
        CGContextSaveGState(context)
        placeholderPath.addClip()
        sh38_placeholderImage.drawInRect(CGRectMake(floor(placeholderRect.minX + 0.5), floor(placeholderRect.minY + 0.5), sh38_placeholderImage.size.width, sh38_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// ImageRect Drawing
        let imageRectRect = CGRectMake(frame.minX + 89, frame.minY + 79.96, 284, 198)
        let imageRectPath = UIBezierPath()
        imageRectPath.moveToPoint(CGPointMake(frame.minX + 89, frame.minY + 120.12))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 89.47, frame.minY + 134.6))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 93.01, frame.minY + 142.19))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 150.22))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 89.75, frame.minY + 159.98))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 90, frame.minY + 183.32))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 95.01, frame.minY + 195.36))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 92.01, frame.minY + 210.41))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 220.44))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 234.48))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 96.02, frame.minY + 276.61), controlPoint1: CGPointMake(frame.minX + 91, frame.minY + 234.48), controlPoint2: CGPointMake(frame.minX + 94.01, frame.minY + 273.6))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 132.08, frame.minY + 276.66), controlPoint1: CGPointMake(frame.minX + 98.02, frame.minY + 279.62), controlPoint2: CGPointMake(frame.minX + 132.08, frame.minY + 276.66))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 177.21, frame.minY + 272.6))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 180.34, frame.minY + 270.99))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 186.23, frame.minY + 270.59))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 200.26, frame.minY + 268.59), controlPoint1: CGPointMake(frame.minX + 186.23, frame.minY + 270.59), controlPoint2: CGPointMake(frame.minX + 193.24, frame.minY + 269.59))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 236.35, frame.minY + 269.59), controlPoint1: CGPointMake(frame.minX + 207.28, frame.minY + 267.58), controlPoint2: CGPointMake(frame.minX + 226.32, frame.minY + 271.6))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 251.38, frame.minY + 264.57), controlPoint1: CGPointMake(frame.minX + 246.37, frame.minY + 267.58), controlPoint2: CGPointMake(frame.minX + 242.36, frame.minY + 265.58))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 283.46, frame.minY + 263.57), controlPoint1: CGPointMake(frame.minX + 260.4, frame.minY + 263.57), controlPoint2: CGPointMake(frame.minX + 283.46, frame.minY + 263.57))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 312.14, frame.minY + 260.86))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 369.66, frame.minY + 255.55), controlPoint1: CGPointMake(frame.minX + 312.14, frame.minY + 260.86), controlPoint2: CGPointMake(frame.minX + 366.65, frame.minY + 259.56))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 367.65, frame.minY + 200.37), controlPoint1: CGPointMake(frame.minX + 372.67, frame.minY + 251.53), controlPoint2: CGPointMake(frame.minX + 370.19, frame.minY + 225.08))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 361.64, frame.minY + 187.33), controlPoint1: CGPointMake(frame.minX + 367.04, frame.minY + 194.35), controlPoint2: CGPointMake(frame.minX + 361.64, frame.minY + 188.12))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 364.65, frame.minY + 177.3), controlPoint1: CGPointMake(frame.minX + 361.64, frame.minY + 183.32), controlPoint2: CGPointMake(frame.minX + 364.65, frame.minY + 177.3))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367.65, frame.minY + 160.25))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367.65, frame.minY + 154.23))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 364.65, frame.minY + 146.21))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367.65, frame.minY + 115.11))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 371.66, frame.minY + 98.06))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 371.66, frame.minY + 83.01), controlPoint1: CGPointMake(frame.minX + 371.66, frame.minY + 98.06), controlPoint2: CGPointMake(frame.minX + 374.67, frame.minY + 85.02))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 326.56, frame.minY + 80), controlPoint1: CGPointMake(frame.minX + 368.66, frame.minY + 81), controlPoint2: CGPointMake(frame.minX + 329.78, frame.minY + 79.72))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 306.51, frame.minY + 82.01), controlPoint1: CGPointMake(frame.minX + 322.32, frame.minY + 80.37), controlPoint2: CGPointMake(frame.minX + 313.54, frame.minY + 81.87))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 287.47, frame.minY + 85.02), controlPoint1: CGPointMake(frame.minX + 299.41, frame.minY + 82.14), controlPoint2: CGPointMake(frame.minX + 294.04, frame.minY + 83.92))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 245.37, frame.minY + 85.02), controlPoint1: CGPointMake(frame.minX + 282.96, frame.minY + 85.77), controlPoint2: CGPointMake(frame.minX + 257.87, frame.minY + 84.87))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 227.32, frame.minY + 87.02), controlPoint1: CGPointMake(frame.minX + 243.82, frame.minY + 85.03), controlPoint2: CGPointMake(frame.minX + 231.64, frame.minY + 86.47))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 201.26, frame.minY + 90.03), controlPoint1: CGPointMake(frame.minX + 218.52, frame.minY + 88.15), controlPoint2: CGPointMake(frame.minX + 210.24, frame.minY + 89.08))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 186.23, frame.minY + 93.04), controlPoint1: CGPointMake(frame.minX + 197.56, frame.minY + 90.43), controlPoint2: CGPointMake(frame.minX + 188.91, frame.minY + 92.72))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 171.19, frame.minY + 100.06), controlPoint1: CGPointMake(frame.minX + 178.98, frame.minY + 93.9), controlPoint2: CGPointMake(frame.minX + 177.74, frame.minY + 99.43))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 141.12, frame.minY + 98.06), controlPoint1: CGPointMake(frame.minX + 159.72, frame.minY + 101.17), controlPoint2: CGPointMake(frame.minX + 150.52, frame.minY + 99.98))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 111.05, frame.minY + 93.04), controlPoint1: CGPointMake(frame.minX + 125.06, frame.minY + 94.77), controlPoint2: CGPointMake(frame.minX + 112.81, frame.minY + 91.79))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 89, frame.minY + 120.12), controlPoint1: CGPointMake(frame.minX + 104.04, frame.minY + 98.06), controlPoint2: CGPointMake(frame.minX + 89, frame.minY + 120.12))
        imageRectPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        imageRectPath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(imageRectRect.minX + 0.5), floor(imageRectRect.minY + 0.65 + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH38(frame frame: CGRect = CGRectMake(89, 54, 462, 356), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH38_PhotoFrame.drawSH38(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH38 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH38
    }

}
