//
//  SH3_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 27.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH3_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH3(frame frame: CGRect = CGRectMake(74, 14, 474, 372), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.blackColor()
        shadow.shadowOffset = CGSizeMake(0.1, -0.1)
        shadow.shadowBlurRadius = 10

        //// Image Declarations
        let sh3_placeholderImage = UIImage(named: "sh3_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 474, 372)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sh3_placeholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sh3_placeholderImage.size.width, sh3_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// ImageRectangle Drawing
        let imageRectangleRect = CGRectMake(frame.minX + 34.69, frame.minY + 26.08, 405, 291)
        let imageRectanglePath = UIBezierPath()
        imageRectanglePath.moveToPoint(CGPointMake(frame.minX + 71.51, frame.minY + 36.63))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 82.89, frame.minY + 38.68), controlPoint1: CGPointMake(frame.minX + 74.41, frame.minY + 37.03), controlPoint2: CGPointMake(frame.minX + 78.32, frame.minY + 38.48))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 105.95, frame.minY + 38), controlPoint1: CGPointMake(frame.minX + 89.52, frame.minY + 38.98), controlPoint2: CGPointMake(frame.minX + 97.55, frame.minY + 38.19))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 136.92, frame.minY + 41), controlPoint1: CGPointMake(frame.minX + 115.1, frame.minY + 37.79), controlPoint2: CGPointMake(frame.minX + 125.26, frame.minY + 41.26))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 154.91, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 142.13, frame.minY + 40.88), controlPoint2: CGPointMake(frame.minX + 150.12, frame.minY + 40.23))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 165.9, frame.minY + 36), controlPoint1: CGPointMake(frame.minX + 159.31, frame.minY + 37.86), controlPoint2: CGPointMake(frame.minX + 160.48, frame.minY + 36.14))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 191.88, frame.minY + 41), controlPoint1: CGPointMake(frame.minX + 173.84, frame.minY + 35.79), controlPoint2: CGPointMake(frame.minX + 183.45, frame.minY + 41.19))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 214.86, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 200.15, frame.minY + 40.81), controlPoint2: CGPointMake(frame.minX + 206.25, frame.minY + 37.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 227.08, frame.minY + 32.35), controlPoint1: CGPointMake(frame.minX + 218.7, frame.minY + 34.02), controlPoint2: CGPointMake(frame.minX + 222.88, frame.minY + 32.57))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 240.84, frame.minY + 30), controlPoint1: CGPointMake(frame.minX + 231.77, frame.minY + 32.1), controlPoint2: CGPointMake(frame.minX + 236.5, frame.minY + 30.13))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 251.65, frame.minY + 29.69), controlPoint1: CGPointMake(frame.minX + 244.44, frame.minY + 29.89), controlPoint2: CGPointMake(frame.minX + 248.05, frame.minY + 29.78))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 267.82, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 257.36, frame.minY + 29.53), controlPoint2: CGPointMake(frame.minX + 262.5, frame.minY + 30.57))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 278.81, frame.minY + 36), controlPoint1: CGPointMake(frame.minX + 271.42, frame.minY + 32.97), controlPoint2: CGPointMake(frame.minX + 275.25, frame.minY + 35.22))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 324.77, frame.minY + 41), controlPoint1: CGPointMake(frame.minX + 292.55, frame.minY + 39.02), controlPoint2: CGPointMake(frame.minX + 311, frame.minY + 40.96))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 342.46, frame.minY + 38.07), controlPoint1: CGPointMake(frame.minX + 331.72, frame.minY + 41.01), controlPoint2: CGPointMake(frame.minX + 337.23, frame.minY + 40.12))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 359.75, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 348.08, frame.minY + 35.85), controlPoint2: CGPointMake(frame.minX + 353.37, frame.minY + 35.45))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 380.11, frame.minY + 33.83), controlPoint1: CGPointMake(frame.minX + 366.82, frame.minY + 34.5), controlPoint2: CGPointMake(frame.minX + 373.66, frame.minY + 34.12))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 396.29, frame.minY + 30.47), controlPoint1: CGPointMake(frame.minX + 386.65, frame.minY + 33.53), controlPoint2: CGPointMake(frame.minX + 391.7, frame.minY + 32.42))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 407.71, frame.minY + 27), controlPoint1: CGPointMake(frame.minX + 400.22, frame.minY + 28.79), controlPoint2: CGPointMake(frame.minX + 403.81, frame.minY + 27.23))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 432.69, frame.minY + 31), controlPoint1: CGPointMake(frame.minX + 419.62, frame.minY + 26.31), controlPoint2: CGPointMake(frame.minX + 425.48, frame.minY + 24))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 434.69, frame.minY + 69.99), controlPoint1: CGPointMake(frame.minX + 439.9, frame.minY + 38), controlPoint2: CGPointMake(frame.minX + 434.69, frame.minY + 65.99))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 424.9, frame.minY + 107), controlPoint1: CGPointMake(frame.minX + 434.69, frame.minY + 70.36), controlPoint2: CGPointMake(frame.minX + 426.9, frame.minY + 98))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 425.9, frame.minY + 125.01), controlPoint1: CGPointMake(frame.minX + 422.48, frame.minY + 117.88), controlPoint2: CGPointMake(frame.minX + 426.69, frame.minY + 120.25))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.17, frame.minY + 139.33), controlPoint1: CGPointMake(frame.minX + 425.02, frame.minY + 130.26), controlPoint2: CGPointMake(frame.minX + 422.31, frame.minY + 134.53))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 419.7, frame.minY + 153.98), controlPoint1: CGPointMake(frame.minX + 420.18, frame.minY + 143.51), controlPoint2: CGPointMake(frame.minX + 419.47, frame.minY + 148.07))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 427.69, frame.minY + 169.98), controlPoint1: CGPointMake(frame.minX + 419.96, frame.minY + 160.84), controlPoint2: CGPointMake(frame.minX + 421.79, frame.minY + 165.22))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 439.68, frame.minY + 184.98), controlPoint1: CGPointMake(frame.minX + 432.87, frame.minY + 174.16), controlPoint2: CGPointMake(frame.minX + 439.19, frame.minY + 178.65))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 434.79, frame.minY + 200.71), controlPoint1: CGPointMake(frame.minX + 439.83, frame.minY + 186.91), controlPoint2: CGPointMake(frame.minX + 435.33, frame.minY + 199.49))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 428.69, frame.minY + 209.97), controlPoint1: CGPointMake(frame.minX + 434.19, frame.minY + 202.09), controlPoint2: CGPointMake(frame.minX + 429.68, frame.minY + 208.47))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.7, frame.minY + 227.97), controlPoint1: CGPointMake(frame.minX + 424.61, frame.minY + 216.16), controlPoint2: CGPointMake(frame.minX + 424.21, frame.minY + 221.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.71, frame.minY + 238.76), controlPoint1: CGPointMake(frame.minX + 420.22, frame.minY + 231.52), controlPoint2: CGPointMake(frame.minX + 423.01, frame.minY + 235.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 422.7, frame.minY + 247.97), controlPoint1: CGPointMake(frame.minX + 421.19, frame.minY + 240.19), controlPoint2: CGPointMake(frame.minX + 422.82, frame.minY + 246.6))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 426.69, frame.minY + 258.97), controlPoint1: CGPointMake(frame.minX + 421.94, frame.minY + 256.81), controlPoint2: CGPointMake(frame.minX + 424.84, frame.minY + 251.62))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 424.21, frame.minY + 266.89), controlPoint1: CGPointMake(frame.minX + 427.35, frame.minY + 261.55), controlPoint2: CGPointMake(frame.minX + 426.06, frame.minY + 263.72))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 422.7, frame.minY + 277.96), controlPoint1: CGPointMake(frame.minX + 423.26, frame.minY + 268.52), controlPoint2: CGPointMake(frame.minX + 423.53, frame.minY + 276.43))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 410.94, frame.minY + 290.75), controlPoint1: CGPointMake(frame.minX + 421.48, frame.minY + 280.21), controlPoint2: CGPointMake(frame.minX + 412.98, frame.minY + 288.9))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 396.72, frame.minY + 298.96), controlPoint1: CGPointMake(frame.minX + 405.76, frame.minY + 295.44), controlPoint2: CGPointMake(frame.minX + 406.9, frame.minY + 298.02))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 359.03, frame.minY + 303.56), controlPoint1: CGPointMake(frame.minX + 386.53, frame.minY + 299.9), controlPoint2: CGPointMake(frame.minX + 363.21, frame.minY + 303.04))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 335.76, frame.minY + 303.96), controlPoint1: CGPointMake(frame.minX + 354.86, frame.minY + 304.08), controlPoint2: CGPointMake(frame.minX + 341.15, frame.minY + 303.96))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 315.52, frame.minY + 307.48), controlPoint1: CGPointMake(frame.minX + 331.52, frame.minY + 303.96), controlPoint2: CGPointMake(frame.minX + 317.85, frame.minY + 305.83))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 286.8, frame.minY + 306.96), controlPoint1: CGPointMake(frame.minX + 313.7, frame.minY + 308.78), controlPoint2: CGPointMake(frame.minX + 293.11, frame.minY + 306.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 259.94, frame.minY + 315.02), controlPoint1: CGPointMake(frame.minX + 281.96, frame.minY + 306.97), controlPoint2: CGPointMake(frame.minX + 262.09, frame.minY + 314.04))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 245.95, frame.minY + 317.02), controlPoint1: CGPointMake(frame.minX + 254.2, frame.minY + 317.63), controlPoint2: CGPointMake(frame.minX + 247.7, frame.minY + 317.01))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 226.85, frame.minY + 312.96), controlPoint1: CGPointMake(frame.minX + 242.4, frame.minY + 317.03), controlPoint2: CGPointMake(frame.minX + 231.28, frame.minY + 314.03))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 214.86, frame.minY + 307.96), controlPoint1: CGPointMake(frame.minX + 222.27, frame.minY + 311.86), controlPoint2: CGPointMake(frame.minX + 219.27, frame.minY + 309.6))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 207.96, frame.minY + 307.02), controlPoint1: CGPointMake(frame.minX + 213.01, frame.minY + 307.27), controlPoint2: CGPointMake(frame.minX + 213.67, frame.minY + 307.17))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 199.87, frame.minY + 308.96), controlPoint1: CGPointMake(frame.minX + 205.89, frame.minY + 306.96), controlPoint2: CGPointMake(frame.minX + 201.93, frame.minY + 309))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 193.19, frame.minY + 312.1), controlPoint1: CGPointMake(frame.minX + 197.65, frame.minY + 308.91), controlPoint2: CGPointMake(frame.minX + 195.42, frame.minY + 310.53))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 186.88, frame.minY + 313.96), controlPoint1: CGPointMake(frame.minX + 191.09, frame.minY + 313.58), controlPoint2: CGPointMake(frame.minX + 188.99, frame.minY + 314.01))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 178.89, frame.minY + 311.96), controlPoint1: CGPointMake(frame.minX + 183.06, frame.minY + 313.85), controlPoint2: CGPointMake(frame.minX + 182.26, frame.minY + 313.61))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 165.9, frame.minY + 308.96), controlPoint1: CGPointMake(frame.minX + 175.45, frame.minY + 310.27), controlPoint2: CGPointMake(frame.minX + 169.45, frame.minY + 310.16))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 152, frame.minY + 306.97), controlPoint1: CGPointMake(frame.minX + 161.44, frame.minY + 307.45), controlPoint2: CGPointMake(frame.minX + 156.74, frame.minY + 307.56))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 140.92, frame.minY + 306.96), controlPoint1: CGPointMake(frame.minX + 148.3, frame.minY + 306.51), controlPoint2: CGPointMake(frame.minX + 144.57, frame.minY + 307.22))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 114.94, frame.minY + 307.96), controlPoint1: CGPointMake(frame.minX + 130.86, frame.minY + 306.23), controlPoint2: CGPointMake(frame.minX + 122.45, frame.minY + 308.39))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 85.96, frame.minY + 305.96), controlPoint1: CGPointMake(frame.minX + 103.8, frame.minY + 307.32), controlPoint2: CGPointMake(frame.minX + 92.38, frame.minY + 306.71))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.97, frame.minY + 299.96), controlPoint1: CGPointMake(frame.minX + 73.55, frame.minY + 304.5), controlPoint2: CGPointMake(frame.minX + 71.97, frame.minY + 299.96))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 62.98, frame.minY + 278.96), controlPoint1: CGPointMake(frame.minX + 71.97, frame.minY + 299.96), controlPoint2: CGPointMake(frame.minX + 63.45, frame.minY + 291.75))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 59.98, frame.minY + 253.97), controlPoint1: CGPointMake(frame.minX + 62.77, frame.minY + 273.22), controlPoint2: CGPointMake(frame.minX + 61.6, frame.minY + 259.99))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 58.98, frame.minY + 246.97), controlPoint1: CGPointMake(frame.minX + 58.82, frame.minY + 249.66), controlPoint2: CGPointMake(frame.minX + 59.05, frame.minY + 253.08))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 54.98, frame.minY + 235.97), controlPoint1: CGPointMake(frame.minX + 58.96, frame.minY + 245.01), controlPoint2: CGPointMake(frame.minX + 55, frame.minY + 237.98))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 42.99, frame.minY + 223.97), controlPoint1: CGPointMake(frame.minX + 54.95, frame.minY + 232.74), controlPoint2: CGPointMake(frame.minX + 45.54, frame.minY + 228.94))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 41, frame.minY + 204.97), controlPoint1: CGPointMake(frame.minX + 39.65, frame.minY + 217.43), controlPoint2: CGPointMake(frame.minX + 41.88, frame.minY + 209.56))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 35.99, frame.minY + 184.98), controlPoint1: CGPointMake(frame.minX + 40.33, frame.minY + 201.53), controlPoint2: CGPointMake(frame.minX + 36, frame.minY + 192.01))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 35, frame.minY + 169.98), controlPoint1: CGPointMake(frame.minX + 35.99, frame.minY + 182.03), controlPoint2: CGPointMake(frame.minX + 36, frame.minY + 173.62))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 38, frame.minY + 144.98), controlPoint1: CGPointMake(frame.minX + 33.47, frame.minY + 164.41), controlPoint2: CGPointMake(frame.minX + 38, frame.minY + 150.85))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 37, frame.minY + 124.99), controlPoint1: CGPointMake(frame.minX + 37.98, frame.minY + 135.22), controlPoint2: CGPointMake(frame.minX + 36.34, frame.minY + 133.17))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 42.99, frame.minY + 106.99), controlPoint1: CGPointMake(frame.minX + 37.14, frame.minY + 123.21), controlPoint2: CGPointMake(frame.minX + 41.35, frame.minY + 111.03))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 46.99, frame.minY + 98.99), controlPoint1: CGPointMake(frame.minX + 44.06, frame.minY + 104.37), controlPoint2: CGPointMake(frame.minX + 46.43, frame.minY + 101.52))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 48.99, frame.minY + 82.99), controlPoint1: CGPointMake(frame.minX + 48.41, frame.minY + 92.62), controlPoint2: CGPointMake(frame.minX + 48, frame.minY + 87.04))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 46.99, frame.minY + 69.99), controlPoint1: CGPointMake(frame.minX + 49.69, frame.minY + 80.12), controlPoint2: CGPointMake(frame.minX + 48.55, frame.minY + 72.89))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 45.99, frame.minY + 65.99), controlPoint1: CGPointMake(frame.minX + 45.37, frame.minY + 66.98), controlPoint2: CGPointMake(frame.minX + 45.34, frame.minY + 68.32))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56.98, frame.minY + 48), controlPoint1: CGPointMake(frame.minX + 47.06, frame.minY + 62.18), controlPoint2: CGPointMake(frame.minX + 55.29, frame.minY + 50.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 64.98, frame.minY + 37), controlPoint1: CGPointMake(frame.minX + 58.65, frame.minY + 45.84), controlPoint2: CGPointMake(frame.minX + 64.55, frame.minY + 37.32))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.51, frame.minY + 36.63), controlPoint1: CGPointMake(frame.minX + 65.21, frame.minY + 36.82), controlPoint2: CGPointMake(frame.minX + 68.22, frame.minY + 36.19))
        imageRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        imageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(imageRectangleRect.minX + 0.5), floor(imageRectangleRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH3(frame frame: CGRect = CGRectMake(74, 14, 474, 372), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH3_PhotoFrame.drawSH3(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH3 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH3
    }

}
