//
//  GlassOvalKeyRing.swift
//  Blagaprint
//
//  Created by Ivan Magda on 28.01.16.
//  Copyright (c) 2016 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class GlassOvalKeyRing : NSObject {

    //// Drawing Methods

    public class func drawKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let frameOvalFillColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.150)
        let frameOvalStrokeColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.100)
        let innerOvalStrokeColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.200)
        let bottomOvalFillColor = UIColor(red: 0.718, green: 0.718, blue: 0.718, alpha: 0.150)
        let keyCircleColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.602)
        let keyCircleStrokeColor = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 1.000)

        //// Shadow Declarations
        let holderShadow = NSShadow()
        holderShadow.shadowColor = UIColor.lightGrayColor()
        holderShadow.shadowOffset = CGSizeMake(3.1, 3.1)
        holderShadow.shadowBlurRadius = 5
        let keyRingShadow = NSShadow()
        keyRingShadow.shadowColor = UIColor.lightGrayColor()
        keyRingShadow.shadowOffset = CGSizeMake(3.1, 2.1)
        keyRingShadow.shadowBlurRadius = 6

        //// KeyRingGroup
        //// ShadowOval Drawing
        let shadowOvalPath = UIBezierPath()
        shadowOvalPath.moveToPoint(CGPointMake(frame.minX + 255, frame.minY + 193.19))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 194.97, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 255, frame.minY + 249.02), controlPoint2: CGPointMake(frame.minX + 225.25, frame.minY + 315))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 157.15, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 185.65, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 157.15, frame.minY + 315))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 129.95, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 157.15, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 138.15, frame.minY + 315))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 65, frame.minY + 193.19), controlPoint1: CGPointMake(frame.minX + 97.19, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 65, frame.minY + 251.59))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160, frame.minY + 61), controlPoint1: CGPointMake(frame.minX + 65, frame.minY + 120.18), controlPoint2: CGPointMake(frame.minX + 107.53, frame.minY + 61))
        shadowOvalPath.addCurveToPoint(CGPointMake(frame.minX + 255, frame.minY + 193.19), controlPoint1: CGPointMake(frame.minX + 212.47, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 255, frame.minY + 120.18))
        shadowOvalPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, keyRingShadow.shadowOffset, keyRingShadow.shadowBlurRadius, (keyRingShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        shadowOvalPath.fill()
        CGContextRestoreGState(context)



        if (imageVisible) {
            //// ImageOval Drawing
            let imageOvalRect = CGRectMake(frame.minX + 100, frame.minY + 95, 120, 186)
            let imageOvalPath = UIBezierPath()
            imageOvalPath.moveToPoint(CGPointMake(frame.minX + 220, frame.minY + 191.8))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 182.09, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 220, frame.minY + 232.68), controlPoint2: CGPointMake(frame.minX + 201.21, frame.minY + 281))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 158.2, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 176.2, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 158.2, frame.minY + 281))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 141.02, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 158.2, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 146.2, frame.minY + 281))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 100, frame.minY + 191.8), controlPoint1: CGPointMake(frame.minX + 120.33, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 100, frame.minY + 234.57))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160, frame.minY + 95), controlPoint1: CGPointMake(frame.minX + 100, frame.minY + 138.34), controlPoint2: CGPointMake(frame.minX + 126.86, frame.minY + 95))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 220, frame.minY + 191.8), controlPoint1: CGPointMake(frame.minX + 193.14, frame.minY + 95), controlPoint2: CGPointMake(frame.minX + 220, frame.minY + 138.34))
            imageOvalPath.closePath()
            CGContextSaveGState(context)
            imageOvalPath.addClip()
            image.drawInRect(CGRectMake(floor(imageOvalRect.minX + 0.5), floor(imageOvalRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
        }


        //// BottomOval Drawing
        let bottomOvalPath = UIBezierPath()
        bottomOvalPath.moveToPoint(CGPointMake(frame.minX + 220, frame.minY + 191.8))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 182.09, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 220, frame.minY + 232.68), controlPoint2: CGPointMake(frame.minX + 201.21, frame.minY + 281))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 158.2, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 176.2, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 158.2, frame.minY + 281))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 141.02, frame.minY + 281), controlPoint1: CGPointMake(frame.minX + 158.2, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 146.2, frame.minY + 281))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 100, frame.minY + 191.8), controlPoint1: CGPointMake(frame.minX + 120.33, frame.minY + 281), controlPoint2: CGPointMake(frame.minX + 100, frame.minY + 234.57))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160, frame.minY + 95), controlPoint1: CGPointMake(frame.minX + 100, frame.minY + 138.34), controlPoint2: CGPointMake(frame.minX + 126.86, frame.minY + 95))
        bottomOvalPath.addCurveToPoint(CGPointMake(frame.minX + 220, frame.minY + 191.8), controlPoint1: CGPointMake(frame.minX + 193.14, frame.minY + 95), controlPoint2: CGPointMake(frame.minX + 220, frame.minY + 138.34))
        bottomOvalPath.closePath()
        bottomOvalFillColor.setFill()
        bottomOvalPath.fill()
        frameOvalStrokeColor.setStroke()
        bottomOvalPath.lineWidth = 0.5
        bottomOvalPath.stroke()


        //// InnerOval Drawing
        let innerOvalPath = UIBezierPath()
        innerOvalPath.moveToPoint(CGPointMake(frame.minX + 247, frame.minY + 192.87))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 192.03, frame.minY + 307), controlPoint1: CGPointMake(frame.minX + 247, frame.minY + 245.17), controlPoint2: CGPointMake(frame.minX + 219.76, frame.minY + 307))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 157.39, frame.minY + 307), controlPoint1: CGPointMake(frame.minX + 183.49, frame.minY + 307), controlPoint2: CGPointMake(frame.minX + 157.39, frame.minY + 307))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 132.48, frame.minY + 307), controlPoint1: CGPointMake(frame.minX + 157.39, frame.minY + 307), controlPoint2: CGPointMake(frame.minX + 139.99, frame.minY + 307))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 73, frame.minY + 192.87), controlPoint1: CGPointMake(frame.minX + 102.48, frame.minY + 307), controlPoint2: CGPointMake(frame.minX + 73, frame.minY + 247.58))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160, frame.minY + 69), controlPoint1: CGPointMake(frame.minX + 73, frame.minY + 124.46), controlPoint2: CGPointMake(frame.minX + 111.95, frame.minY + 69))
        innerOvalPath.addCurveToPoint(CGPointMake(frame.minX + 247, frame.minY + 192.87), controlPoint1: CGPointMake(frame.minX + 208.05, frame.minY + 69), controlPoint2: CGPointMake(frame.minX + 247, frame.minY + 124.46))
        innerOvalPath.closePath()
        UIColor.clearColor().setFill()
        innerOvalPath.fill()
        innerOvalStrokeColor.setStroke()
        innerOvalPath.lineWidth = 15
        CGContextSaveGState(context)
        CGContextSetLineDash(context, 0, [1, 1], 2)
        innerOvalPath.stroke()
        CGContextRestoreGState(context)


        //// FrameOval Drawing
        let frameOvalPath = UIBezierPath()
        frameOvalPath.moveToPoint(CGPointMake(frame.minX + 255, frame.minY + 193.19))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 194.97, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 255, frame.minY + 249.02), controlPoint2: CGPointMake(frame.minX + 225.25, frame.minY + 315))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 157.15, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 185.65, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 157.15, frame.minY + 315))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 129.95, frame.minY + 315), controlPoint1: CGPointMake(frame.minX + 157.15, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 138.15, frame.minY + 315))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 65, frame.minY + 193.19), controlPoint1: CGPointMake(frame.minX + 97.19, frame.minY + 315), controlPoint2: CGPointMake(frame.minX + 65, frame.minY + 251.59))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160, frame.minY + 61), controlPoint1: CGPointMake(frame.minX + 65, frame.minY + 120.18), controlPoint2: CGPointMake(frame.minX + 107.53, frame.minY + 61))
        frameOvalPath.addCurveToPoint(CGPointMake(frame.minX + 255, frame.minY + 193.19), controlPoint1: CGPointMake(frame.minX + 212.47, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 255, frame.minY + 120.18))
        frameOvalPath.closePath()
        frameOvalFillColor.setFill()
        frameOvalPath.fill()
        frameOvalStrokeColor.setStroke()
        frameOvalPath.lineWidth = 1
        frameOvalPath.stroke()




        //// KeyHolderGroup
        //// KeyCircle Drawing
        let keyCirclePath = UIBezierPath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 9.71))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 146.8, frame.minY + 13.86), controlPoint1: CGPointMake(frame.minX + 154.92, frame.minY + 9.71), controlPoint2: CGPointMake(frame.minX + 150.45, frame.minY + 11.25))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 137.46, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 141.15, frame.minY + 17.9), controlPoint2: CGPointMake(frame.minX + 137.46, frame.minY + 24.52))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 54.29), controlPoint1: CGPointMake(frame.minX + 137.46, frame.minY + 44.31), controlPoint2: CGPointMake(frame.minX + 147.44, frame.minY + 54.29))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 182.04, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 172.06, frame.minY + 54.29), controlPoint2: CGPointMake(frame.minX + 182.04, frame.minY + 44.31))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 9.71), controlPoint1: CGPointMake(frame.minX + 182.04, frame.minY + 19.69), controlPoint2: CGPointMake(frame.minX + 172.06, frame.minY + 9.71))
        keyCirclePath.closePath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 185.75, frame.minY + 32))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 58), controlPoint1: CGPointMake(frame.minX + 185.75, frame.minY + 46.36), controlPoint2: CGPointMake(frame.minX + 174.11, frame.minY + 58))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 133.75, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 145.39, frame.minY + 58), controlPoint2: CGPointMake(frame.minX + 133.75, frame.minY + 46.36))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 143.89, frame.minY + 11.4), controlPoint1: CGPointMake(frame.minX + 133.75, frame.minY + 23.61), controlPoint2: CGPointMake(frame.minX + 137.72, frame.minY + 16.15))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 6), controlPoint1: CGPointMake(frame.minX + 148.28, frame.minY + 8.01), controlPoint2: CGPointMake(frame.minX + 153.78, frame.minY + 6))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 185.75, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 174.11, frame.minY + 6), controlPoint2: CGPointMake(frame.minX + 185.75, frame.minY + 17.64))
        keyCirclePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, holderShadow.shadowOffset, holderShadow.shadowBlurRadius, (holderShadow.shadowColor as! UIColor).CGColor)
        keyCircleColor.setFill()
        keyCirclePath.fill()
        CGContextRestoreGState(context)

        keyCircleStrokeColor.setStroke()
        keyCirclePath.lineWidth = 0.5
        keyCirclePath.stroke()


        //// ChainRectangle Drawing
        let chainRectanglePath = UIBezierPath()
        chainRectanglePath.moveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 54))
        chainRectanglePath.addLineToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 61))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 64), controlPoint1: CGPointMake(frame.minX + 158.33, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 157.58, frame.minY + 63.25))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 64), controlPoint1: CGPointMake(frame.minX + 159.08, frame.minY + 64.75), controlPoint2: CGPointMake(frame.minX + 160.58, frame.minY + 64.75))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 61), controlPoint1: CGPointMake(frame.minX + 162.08, frame.minY + 63.25), controlPoint2: CGPointMake(frame.minX + 161.33, frame.minY + 61))
        chainRectanglePath.addLineToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 54))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 160.33, frame.minY + 50), controlPoint1: CGPointMake(frame.minX + 161.33, frame.minY + 54), controlPoint2: CGPointMake(frame.minX + 162.33, frame.minY + 50))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 54), controlPoint1: CGPointMake(frame.minX + 158.33, frame.minY + 50), controlPoint2: CGPointMake(frame.minX + 158.33, frame.minY + 54))
        chainRectanglePath.closePath()
        UIColor.grayColor().setFill()
        chainRectanglePath.fill()
    }

    //// Generated Images

    public class func imageOfKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            GlassOvalKeyRing.drawKeyRing(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), image: image, imageVisible: imageVisible)

        let imageOfKeyRing = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfKeyRing
    }

}
