//
//  HeartKeyRing.swift
//  Blagaprint
//
//  Created by Ivan Magda on 15.01.16.
//  Copyright (c) 2016 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class HeartKeyRing : NSObject {

    //// Drawing Methods

    public class func drawKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color2 = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.602)
        let color3 = UIColor(red: 0.916, green: 0.916, blue: 0.916, alpha: 0.800)

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.lightGrayColor()
        shadow.shadowOffset = CGSizeMake(3.1, 3.1)
        shadow.shadowBlurRadius = 5
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.lightGrayColor()
        outerShadow.shadowOffset = CGSizeMake(3.1, 3.1)
        outerShadow.shadowBlurRadius = 5

        //// Oval Drawing
        let ovalPath = UIBezierPath()
        ovalPath.moveToPoint(CGPointMake(frame.minX + 226, frame.minY + 62))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 273.25, frame.minY + 91.92), controlPoint1: CGPointMake(frame.minX + 247.53, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 263.53, frame.minY + 70.6))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 276.19, frame.minY + 190.65), controlPoint1: CGPointMake(frame.minX + 290.87, frame.minY + 130.55), controlPoint2: CGPointMake(frame.minX + 286.64, frame.minY + 171.36))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 160.71, frame.minY + 310.33), controlPoint1: CGPointMake(frame.minX + 247.88, frame.minY + 242.95), controlPoint2: CGPointMake(frame.minX + 180.28, frame.minY + 310.33))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 43.28, frame.minY + 190.65), controlPoint1: CGPointMake(frame.minX + 141.14, frame.minY + 310.33), controlPoint2: CGPointMake(frame.minX + 63.79, frame.minY + 241.96))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 53.06, frame.minY + 91.92), controlPoint1: CGPointMake(frame.minX + 35.02, frame.minY + 170), controlPoint2: CGPointMake(frame.minX + 26.89, frame.minY + 134.31))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 92, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 62.85, frame.minY + 76.07), controlPoint2: CGPointMake(frame.minX + 74.2, frame.minY + 66.33))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 160.71, frame.minY + 115.32), controlPoint1: CGPointMake(frame.minX + 144.85, frame.minY + 49.12), controlPoint2: CGPointMake(frame.minX + 157.21, frame.minY + 115.32))
        ovalPath.addCurveToPoint(CGPointMake(frame.minX + 226, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 164.06, frame.minY + 115.32), controlPoint2: CGPointMake(frame.minX + 180.76, frame.minY + 64.08))
        ovalPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)

        UIColor.lightGrayColor().setStroke()
        ovalPath.lineWidth = 0.5
        ovalPath.stroke()


        if (imageVisible) {
            //// ImageOval Drawing
            let imageOvalRect = CGRectMake(frame.minX + 35.25, frame.minY + 60.33, 250, 250)
            let imageOvalPath = UIBezierPath()
            imageOvalPath.moveToPoint(CGPointMake(frame.minX + 226, frame.minY + 61.99))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 273.25, frame.minY + 91.91), controlPoint1: CGPointMake(frame.minX + 247.53, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 263.53, frame.minY + 70.59))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 276.19, frame.minY + 190.65), controlPoint1: CGPointMake(frame.minX + 290.87, frame.minY + 130.55), controlPoint2: CGPointMake(frame.minX + 286.64, frame.minY + 171.36))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160.71, frame.minY + 310.33), controlPoint1: CGPointMake(frame.minX + 247.88, frame.minY + 242.95), controlPoint2: CGPointMake(frame.minX + 180.28, frame.minY + 310.33))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 43.28, frame.minY + 190.65), controlPoint1: CGPointMake(frame.minX + 141.14, frame.minY + 310.33), controlPoint2: CGPointMake(frame.minX + 63.79, frame.minY + 241.96))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 53.06, frame.minY + 91.91), controlPoint1: CGPointMake(frame.minX + 35.02, frame.minY + 169.99), controlPoint2: CGPointMake(frame.minX + 26.89, frame.minY + 134.31))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 92, frame.minY + 61.99), controlPoint1: CGPointMake(frame.minX + 62.85, frame.minY + 76.06), controlPoint2: CGPointMake(frame.minX + 74.2, frame.minY + 66.33))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 160.71, frame.minY + 115.32), controlPoint1: CGPointMake(frame.minX + 144.85, frame.minY + 49.11), controlPoint2: CGPointMake(frame.minX + 157.21, frame.minY + 115.32))
            imageOvalPath.addCurveToPoint(CGPointMake(frame.minX + 226, frame.minY + 61.99), controlPoint1: CGPointMake(frame.minX + 164.06, frame.minY + 115.32), controlPoint2: CGPointMake(frame.minX + 180.76, frame.minY + 64.07))
            imageOvalPath.closePath()
            CGContextSaveGState(context)
            CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
            CGContextBeginTransparencyLayer(context, nil)
            CGContextSaveGState(context)
            imageOvalPath.addClip()
            image.drawInRect(CGRectMake(floor(imageOvalRect.minX + 0.5), floor(imageOvalRect.minY - 0.67 + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
            CGContextEndTransparencyLayer(context)
            CGContextRestoreGState(context)

        }


        //// Separator Drawing
        let separatorPath = UIBezierPath()
        separatorPath.moveToPoint(CGPointMake(frame.minX + 160.5, frame.minY + 115))
        separatorPath.addCurveToPoint(CGPointMake(frame.minX + 166.75, frame.minY + 136.28), controlPoint1: CGPointMake(frame.minX + 160.5, frame.minY + 115), controlPoint2: CGPointMake(frame.minX + 166.84, frame.minY + 123.68))
        separatorPath.addCurveToPoint(CGPointMake(frame.minX + 159.25, frame.minY + 199.28), controlPoint1: CGPointMake(frame.minX + 166.62, frame.minY + 153.36), controlPoint2: CGPointMake(frame.minX + 158.84, frame.minY + 178.06))
        separatorPath.addCurveToPoint(CGPointMake(frame.minX + 148.5, frame.minY + 260.03), controlPoint1: CGPointMake(frame.minX + 160.25, frame.minY + 251.28), controlPoint2: CGPointMake(frame.minX + 148.5, frame.minY + 244.31))
        separatorPath.addCurveToPoint(CGPointMake(frame.minX + 160.5, frame.minY + 310), controlPoint1: CGPointMake(frame.minX + 148.5, frame.minY + 290.35), controlPoint2: CGPointMake(frame.minX + 160.5, frame.minY + 310))
        UIColor.darkGrayColor().setStroke()
        separatorPath.lineWidth = 1
        separatorPath.stroke()


        //// Hole Drawing
        let holePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 72.25, frame.minY + 83.75, 30, 30))
        UIColor.darkGrayColor().setFill()
        holePath.fill()


        //// KeyCircle Drawing
        let keyCirclePath = UIBezierPath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 42, frame.minY + 12))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 24.57, frame.minY + 17.58), controlPoint1: CGPointMake(frame.minX + 35.5, frame.minY + 12), controlPoint2: CGPointMake(frame.minX + 29.48, frame.minY + 14.07))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 12, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 16.96, frame.minY + 23.02), controlPoint2: CGPointMake(frame.minX + 12, frame.minY + 31.93))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 42, frame.minY + 72), controlPoint1: CGPointMake(frame.minX + 12, frame.minY + 58.57), controlPoint2: CGPointMake(frame.minX + 25.43, frame.minY + 72))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 72, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 58.57, frame.minY + 72), controlPoint2: CGPointMake(frame.minX + 72, frame.minY + 58.57))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 42, frame.minY + 12), controlPoint1: CGPointMake(frame.minX + 72, frame.minY + 25.43), controlPoint2: CGPointMake(frame.minX + 58.57, frame.minY + 12))
        keyCirclePath.closePath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 77, frame.minY + 42))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 42, frame.minY + 77), controlPoint1: CGPointMake(frame.minX + 77, frame.minY + 61.33), controlPoint2: CGPointMake(frame.minX + 61.33, frame.minY + 77))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 7, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 22.67, frame.minY + 77), controlPoint2: CGPointMake(frame.minX + 7, frame.minY + 61.33))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 20.65, frame.minY + 14.27), controlPoint1: CGPointMake(frame.minX + 7, frame.minY + 30.71), controlPoint2: CGPointMake(frame.minX + 12.35, frame.minY + 20.67))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 42, frame.minY + 7), controlPoint1: CGPointMake(frame.minX + 26.56, frame.minY + 9.71), controlPoint2: CGPointMake(frame.minX + 33.96, frame.minY + 7))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 77, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 61.33, frame.minY + 7), controlPoint2: CGPointMake(frame.minX + 77, frame.minY + 22.67))
        keyCirclePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        color2.setFill()
        keyCirclePath.fill()
        CGContextRestoreGState(context)

        UIColor.grayColor().setStroke()
        keyCirclePath.lineWidth = 0.5
        keyCirclePath.stroke()


        //// Brace Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 37, frame.minY + 64)
        CGContextRotateCTM(context, -20 * CGFloat(M_PI) / 180)

        let bracePath = UIBezierPath()
        bracePath.moveToPoint(CGPointMake(14.51, 47.85))
        bracePath.addCurveToPoint(CGPointMake(32.77, 69.83), controlPoint1: CGPointMake(15.59, 65.51), controlPoint2: CGPointMake(20.27, 69.83))
        bracePath.addCurveToPoint(CGPointMake(55.38, 49.83), controlPoint1: CGPointMake(45.27, 69.83), controlPoint2: CGPointMake(56.15, 68.2))
        bracePath.addCurveToPoint(CGPointMake(22, 0.86), controlPoint1: CGPointMake(54.62, 31.46), controlPoint2: CGPointMake(22, 0.86))
        bracePath.addLineToPoint(CGPointMake(-0, 0))
        bracePath.addCurveToPoint(CGPointMake(14.51, 47.85), controlPoint1: CGPointMake(-0, 0), controlPoint2: CGPointMake(13.43, 30.19))
        bracePath.closePath()
        color3.setFill()
        bracePath.fill()
        UIColor.lightGrayColor().setStroke()
        bracePath.lineWidth = 0.5
        bracePath.stroke()

        CGContextRestoreGState(context)


        //// Hole 2 Drawing
        let hole2Path = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 221.25, frame.minY + 76.75, 30, 30))
        UIColor.darkGrayColor().setFill()
        hole2Path.fill()


        //// KeyCircle 2 Drawing
        let keyCircle2Path = UIBezierPath()
        keyCircle2Path.moveToPoint(CGPointMake(frame.minX + 280.25, frame.minY + 9.75))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 262.82, frame.minY + 15.33), controlPoint1: CGPointMake(frame.minX + 273.75, frame.minY + 9.75), controlPoint2: CGPointMake(frame.minX + 267.73, frame.minY + 11.82))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 250.25, frame.minY + 39.75), controlPoint1: CGPointMake(frame.minX + 255.21, frame.minY + 20.77), controlPoint2: CGPointMake(frame.minX + 250.25, frame.minY + 29.68))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 280.25, frame.minY + 69.75), controlPoint1: CGPointMake(frame.minX + 250.25, frame.minY + 56.32), controlPoint2: CGPointMake(frame.minX + 263.68, frame.minY + 69.75))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 310.25, frame.minY + 39.75), controlPoint1: CGPointMake(frame.minX + 296.82, frame.minY + 69.75), controlPoint2: CGPointMake(frame.minX + 310.25, frame.minY + 56.32))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 280.25, frame.minY + 9.75), controlPoint1: CGPointMake(frame.minX + 310.25, frame.minY + 23.18), controlPoint2: CGPointMake(frame.minX + 296.82, frame.minY + 9.75))
        keyCircle2Path.closePath()
        keyCircle2Path.moveToPoint(CGPointMake(frame.minX + 315.25, frame.minY + 39.75))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 280.25, frame.minY + 74.75), controlPoint1: CGPointMake(frame.minX + 315.25, frame.minY + 59.08), controlPoint2: CGPointMake(frame.minX + 299.58, frame.minY + 74.75))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 245.25, frame.minY + 39.75), controlPoint1: CGPointMake(frame.minX + 260.92, frame.minY + 74.75), controlPoint2: CGPointMake(frame.minX + 245.25, frame.minY + 59.08))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 258.9, frame.minY + 12.02), controlPoint1: CGPointMake(frame.minX + 245.25, frame.minY + 28.46), controlPoint2: CGPointMake(frame.minX + 250.6, frame.minY + 18.42))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 280.25, frame.minY + 4.75), controlPoint1: CGPointMake(frame.minX + 264.81, frame.minY + 7.46), controlPoint2: CGPointMake(frame.minX + 272.21, frame.minY + 4.75))
        keyCircle2Path.addCurveToPoint(CGPointMake(frame.minX + 315.25, frame.minY + 39.75), controlPoint1: CGPointMake(frame.minX + 299.58, frame.minY + 4.75), controlPoint2: CGPointMake(frame.minX + 315.25, frame.minY + 20.42))
        keyCircle2Path.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        color2.setFill()
        keyCircle2Path.fill()
        CGContextRestoreGState(context)

        UIColor.grayColor().setStroke()
        keyCircle2Path.lineWidth = 0.5
        keyCircle2Path.stroke()


        //// Brace 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 261.91, frame.minY + 38.03)
        CGContextRotateCTM(context, 62 * CGFloat(M_PI) / 180)

        let brace2Path = UIBezierPath()
        brace2Path.moveToPoint(CGPointMake(14.51, 47.85))
        brace2Path.addCurveToPoint(CGPointMake(32.77, 69.83), controlPoint1: CGPointMake(15.59, 65.51), controlPoint2: CGPointMake(20.27, 69.83))
        brace2Path.addCurveToPoint(CGPointMake(55.38, 49.83), controlPoint1: CGPointMake(45.27, 69.83), controlPoint2: CGPointMake(56.15, 68.2))
        brace2Path.addCurveToPoint(CGPointMake(18.96, -10.7), controlPoint1: CGPointMake(54.62, 31.46), controlPoint2: CGPointMake(18.96, -10.7))
        brace2Path.addLineToPoint(CGPointMake(-0, 0))
        brace2Path.addCurveToPoint(CGPointMake(14.51, 47.85), controlPoint1: CGPointMake(-0, 0), controlPoint2: CGPointMake(13.43, 30.19))
        brace2Path.closePath()
        color3.setFill()
        brace2Path.fill()
        UIColor.lightGrayColor().setStroke()
        brace2Path.lineWidth = 0.5
        brace2Path.stroke()

        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            HeartKeyRing.drawKeyRing(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), image: image, imageVisible: imageVisible)

        let imageOfKeyRing = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfKeyRing
    }

}
