//
//  RectangleKeyRing.swift
//  Blagaprint
//
//  Created by Ivan Magda on 28.01.16.
//  Copyright (c) 2016 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class RectangleKeyRing : NSObject {

    //// Drawing Methods

    public class func drawKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let keyCircleColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.602)
        let upperRectangleBackgroundColor = UIColor(red: 0.576, green: 0.576, blue: 0.576, alpha: 0.100)
        let middleRectangleStrokeColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.500)
        let middleRectangleBackgroundColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.050)
        let upperRectangleStrokeColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1.000)
        let bottomRectangleStrokeColor = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1.000)
        let keyCircleStrokeColor = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 1.000)

        //// Shadow Declarations
        let holderShadow = NSShadow()
        holderShadow.shadowColor = UIColor.lightGrayColor()
        holderShadow.shadowOffset = CGSizeMake(3.1, 3.1)
        holderShadow.shadowBlurRadius = 5
        let keyRingShadow = NSShadow()
        keyRingShadow.shadowColor = UIColor.lightGrayColor()
        keyRingShadow.shadowOffset = CGSizeMake(3.1, 2.1)
        keyRingShadow.shadowBlurRadius = 5

        //// KeyRingRectangleGroup
        //// KeyRingShadowRectangle Drawing
        let keyRingShadowRectanglePath = UIBezierPath()
        keyRingShadowRectanglePath.moveToPoint(CGPointMake(frame.minX + 65, frame.minY + 102.07))
        keyRingShadowRectanglePath.addLineToPoint(CGPointMake(frame.minX + 65, frame.minY + 283.05))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.71, frame.minY + 307.58), controlPoint1: CGPointMake(frame.minX + 65, frame.minY + 283.05), controlPoint2: CGPointMake(frame.minX + 64.58, frame.minY + 299.6))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 93.5, frame.minY + 314.99), controlPoint1: CGPointMake(frame.minX + 78.83, frame.minY + 315.57), controlPoint2: CGPointMake(frame.minX + 93.5, frame.minY + 314.99))
        keyRingShadowRectanglePath.addLineToPoint(CGPointMake(frame.minX + 226.5, frame.minY + 314.99))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 248.29, frame.minY + 307.58), controlPoint1: CGPointMake(frame.minX + 226.5, frame.minY + 314.99), controlPoint2: CGPointMake(frame.minX + 241.17, frame.minY + 315.57))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 255, frame.minY + 283.05), controlPoint1: CGPointMake(frame.minX + 255.42, frame.minY + 299.6), controlPoint2: CGPointMake(frame.minX + 255, frame.minY + 283.05))
        keyRingShadowRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 102.07))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 248.29, frame.minY + 77.54), controlPoint1: CGPointMake(frame.minX + 255, frame.minY + 102.07), controlPoint2: CGPointMake(frame.minX + 255.42, frame.minY + 85.52))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 226.5, frame.minY + 70.13), controlPoint1: CGPointMake(frame.minX + 241.17, frame.minY + 69.55), controlPoint2: CGPointMake(frame.minX + 226.5, frame.minY + 70.13))
        keyRingShadowRectanglePath.addLineToPoint(CGPointMake(frame.minX + 93.5, frame.minY + 70.13))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.71, frame.minY + 76.52), controlPoint1: CGPointMake(frame.minX + 93.5, frame.minY + 70.13), controlPoint2: CGPointMake(frame.minX + 78.83, frame.minY + 68.53))
        keyRingShadowRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 65, frame.minY + 102.07), controlPoint1: CGPointMake(frame.minX + 64.58, frame.minY + 84.5), controlPoint2: CGPointMake(frame.minX + 65, frame.minY + 102.07))
        keyRingShadowRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, keyRingShadow.shadowOffset, keyRingShadow.shadowBlurRadius, (keyRingShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        keyRingShadowRectanglePath.fill()
        CGContextRestoreGState(context)



        //// KeyRingBottomRectangle Drawing
        let keyRingBottomRectanglePath = UIBezierPath()
        keyRingBottomRectanglePath.moveToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 109.34))
        keyRingBottomRectanglePath.addLineToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 275.55))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 299.01), controlPoint1: CGPointMake(frame.minX + 75.1, frame.minY + 275.55), controlPoint2: CGPointMake(frame.minX + 73.83, frame.minY + 291.68))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 100.59, frame.minY + 304.88), controlPoint1: CGPointMake(frame.minX + 86.57, frame.minY + 306.35), controlPoint2: CGPointMake(frame.minX + 100.59, frame.minY + 304.88))
        keyRingBottomRectanglePath.addLineToPoint(CGPointMake(frame.minX + 219.51, frame.minY + 304.88))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 238.9, frame.minY + 297.99), controlPoint1: CGPointMake(frame.minX + 219.51, frame.minY + 304.88), controlPoint2: CGPointMake(frame.minX + 232.53, frame.minY + 305.32))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 245, frame.minY + 275.55), controlPoint1: CGPointMake(frame.minX + 245.27, frame.minY + 290.66), controlPoint2: CGPointMake(frame.minX + 245, frame.minY + 275.55))
        keyRingBottomRectanglePath.addLineToPoint(CGPointMake(frame.minX + 245, frame.minY + 109.34))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 238.9, frame.minY + 86.89), controlPoint1: CGPointMake(frame.minX + 245, frame.minY + 109.34), controlPoint2: CGPointMake(frame.minX + 245.27, frame.minY + 94.23))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 219.51, frame.minY + 80.01), controlPoint1: CGPointMake(frame.minX + 232.53, frame.minY + 79.56), controlPoint2: CGPointMake(frame.minX + 219.51, frame.minY + 80.01))
        keyRingBottomRectanglePath.addLineToPoint(CGPointMake(frame.minX + 100.59, frame.minY + 80.01))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 86.89), controlPoint1: CGPointMake(frame.minX + 100.59, frame.minY + 80.01), controlPoint2: CGPointMake(frame.minX + 86.57, frame.minY + 79.56))
        keyRingBottomRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 109.34), controlPoint1: CGPointMake(frame.minX + 73.83, frame.minY + 94.23), controlPoint2: CGPointMake(frame.minX + 75.1, frame.minY + 109.34))
        keyRingBottomRectanglePath.closePath()
        bottomRectangleStrokeColor.setStroke()
        keyRingBottomRectanglePath.lineWidth = 0.5
        keyRingBottomRectanglePath.stroke()


        if (imageVisible) {
            //// KeyRingImageRectangle Drawing
            let keyRingImageRectangleRect = CGRectMake(frame.minX + 75, frame.minY + 80, 170, 225)
            let keyRingImageRectanglePath = UIBezierPath()
            keyRingImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 109.34))
            keyRingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 275.55))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 299.01), controlPoint1: CGPointMake(frame.minX + 75.1, frame.minY + 275.55), controlPoint2: CGPointMake(frame.minX + 73.83, frame.minY + 291.68))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 100.59, frame.minY + 304.88), controlPoint1: CGPointMake(frame.minX + 86.57, frame.minY + 306.35), controlPoint2: CGPointMake(frame.minX + 100.59, frame.minY + 304.88))
            keyRingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 219.51, frame.minY + 304.88))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 238.9, frame.minY + 297.99), controlPoint1: CGPointMake(frame.minX + 219.51, frame.minY + 304.88), controlPoint2: CGPointMake(frame.minX + 232.53, frame.minY + 305.32))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 245, frame.minY + 275.55), controlPoint1: CGPointMake(frame.minX + 245.27, frame.minY + 290.66), controlPoint2: CGPointMake(frame.minX + 245, frame.minY + 275.55))
            keyRingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 245, frame.minY + 109.34))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 238.9, frame.minY + 86.89), controlPoint1: CGPointMake(frame.minX + 245, frame.minY + 109.34), controlPoint2: CGPointMake(frame.minX + 245.27, frame.minY + 94.23))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 219.51, frame.minY + 80.01), controlPoint1: CGPointMake(frame.minX + 232.53, frame.minY + 79.56), controlPoint2: CGPointMake(frame.minX + 219.51, frame.minY + 80.01))
            keyRingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 100.59, frame.minY + 80.01))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 80.2, frame.minY + 86.89), controlPoint1: CGPointMake(frame.minX + 100.59, frame.minY + 80.01), controlPoint2: CGPointMake(frame.minX + 86.57, frame.minY + 79.56))
            keyRingImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 75.1, frame.minY + 109.34), controlPoint1: CGPointMake(frame.minX + 73.83, frame.minY + 94.23), controlPoint2: CGPointMake(frame.minX + 75.1, frame.minY + 109.34))
            keyRingImageRectanglePath.closePath()
            CGContextSaveGState(context)
            keyRingImageRectanglePath.addClip()
            image.drawInRect(CGRectMake(floor(keyRingImageRectangleRect.minX + 0.5), floor(keyRingImageRectangleRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
        }


        //// KeyRingMiddleRectangle Drawing
        let keyRingMiddleRectanglePath = UIBezierPath()
        keyRingMiddleRectanglePath.moveToPoint(CGPointMake(frame.minX + 70, frame.minY + 105.76))
        keyRingMiddleRectanglePath.addLineToPoint(CGPointMake(frame.minX + 70, frame.minY + 279.36))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 76.4, frame.minY + 302.84), controlPoint1: CGPointMake(frame.minX + 70, frame.minY + 279.36), controlPoint2: CGPointMake(frame.minX + 69.65, frame.minY + 295.18))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 97, frame.minY + 309.99), controlPoint1: CGPointMake(frame.minX + 83.15, frame.minY + 310.5), controlPoint2: CGPointMake(frame.minX + 97, frame.minY + 309.99))
        keyRingMiddleRectanglePath.addLineToPoint(CGPointMake(frame.minX + 223, frame.minY + 309.99))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 243.6, frame.minY + 302.84), controlPoint1: CGPointMake(frame.minX + 223, frame.minY + 309.99), controlPoint2: CGPointMake(frame.minX + 236.85, frame.minY + 310.5))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 250, frame.minY + 279.36), controlPoint1: CGPointMake(frame.minX + 250.35, frame.minY + 295.18), controlPoint2: CGPointMake(frame.minX + 250, frame.minY + 279.36))
        keyRingMiddleRectanglePath.addLineToPoint(CGPointMake(frame.minX + 250, frame.minY + 105.76))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 243.6, frame.minY + 81.25), controlPoint1: CGPointMake(frame.minX + 250, frame.minY + 105.76), controlPoint2: CGPointMake(frame.minX + 250.35, frame.minY + 88.91))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 223, frame.minY + 75.13), controlPoint1: CGPointMake(frame.minX + 236.85, frame.minY + 73.59), controlPoint2: CGPointMake(frame.minX + 223, frame.minY + 75.13))
        keyRingMiddleRectanglePath.addLineToPoint(CGPointMake(frame.minX + 97, frame.minY + 75.13))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 76.4, frame.minY + 81.25), controlPoint1: CGPointMake(frame.minX + 97, frame.minY + 75.13), controlPoint2: CGPointMake(frame.minX + 83.15, frame.minY + 73.59))
        keyRingMiddleRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 70, frame.minY + 105.76), controlPoint1: CGPointMake(frame.minX + 69.65, frame.minY + 88.91), controlPoint2: CGPointMake(frame.minX + 70, frame.minY + 105.76))
        keyRingMiddleRectanglePath.closePath()
        middleRectangleBackgroundColor.setFill()
        keyRingMiddleRectanglePath.fill()
        middleRectangleStrokeColor.setStroke()
        keyRingMiddleRectanglePath.lineWidth = 5
        keyRingMiddleRectanglePath.stroke()


        //// KeyRingUpperRectangle Drawing
        let keyRingUpperRectanglePath = UIBezierPath()
        keyRingUpperRectanglePath.moveToPoint(CGPointMake(frame.minX + 65, frame.minY + 102.07))
        keyRingUpperRectanglePath.addLineToPoint(CGPointMake(frame.minX + 65, frame.minY + 283.05))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.71, frame.minY + 307.58), controlPoint1: CGPointMake(frame.minX + 65, frame.minY + 283.05), controlPoint2: CGPointMake(frame.minX + 64.58, frame.minY + 299.6))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 93.5, frame.minY + 314.99), controlPoint1: CGPointMake(frame.minX + 78.83, frame.minY + 315.57), controlPoint2: CGPointMake(frame.minX + 93.5, frame.minY + 314.99))
        keyRingUpperRectanglePath.addLineToPoint(CGPointMake(frame.minX + 226.5, frame.minY + 314.99))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 248.29, frame.minY + 307.58), controlPoint1: CGPointMake(frame.minX + 226.5, frame.minY + 314.99), controlPoint2: CGPointMake(frame.minX + 241.17, frame.minY + 315.57))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 255, frame.minY + 283.05), controlPoint1: CGPointMake(frame.minX + 255.42, frame.minY + 299.6), controlPoint2: CGPointMake(frame.minX + 255, frame.minY + 283.05))
        keyRingUpperRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 102.07))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 248.29, frame.minY + 77.54), controlPoint1: CGPointMake(frame.minX + 255, frame.minY + 102.07), controlPoint2: CGPointMake(frame.minX + 255.42, frame.minY + 85.52))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 226.5, frame.minY + 70.13), controlPoint1: CGPointMake(frame.minX + 241.17, frame.minY + 69.55), controlPoint2: CGPointMake(frame.minX + 226.5, frame.minY + 70.13))
        keyRingUpperRectanglePath.addLineToPoint(CGPointMake(frame.minX + 93.5, frame.minY + 70.13))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.71, frame.minY + 76.52), controlPoint1: CGPointMake(frame.minX + 93.5, frame.minY + 70.13), controlPoint2: CGPointMake(frame.minX + 78.83, frame.minY + 68.53))
        keyRingUpperRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 65, frame.minY + 102.07), controlPoint1: CGPointMake(frame.minX + 64.58, frame.minY + 84.5), controlPoint2: CGPointMake(frame.minX + 65, frame.minY + 102.07))
        keyRingUpperRectanglePath.closePath()
        upperRectangleBackgroundColor.setFill()
        keyRingUpperRectanglePath.fill()
        upperRectangleStrokeColor.setStroke()
        keyRingUpperRectanglePath.lineWidth = 0.5
        keyRingUpperRectanglePath.stroke()




        //// KeyHolderGroup
        //// BottomHolder Drawing
        let bottomHolderPath = UIBezierPath()
        bottomHolderPath.moveToPoint(CGPointMake(frame.minX + 131.04, frame.minY + 69.75))
        bottomHolderPath.addLineToPoint(CGPointMake(frame.minX + 188.96, frame.minY + 69.75))
        bottomHolderPath.addCurveToPoint(CGPointMake(frame.minX + 187.03, frame.minY + 63.38), controlPoint1: CGPointMake(frame.minX + 188.96, frame.minY + 69.75), controlPoint2: CGPointMake(frame.minX + 189.44, frame.minY + 65.37))
        bottomHolderPath.addCurveToPoint(CGPointMake(frame.minX + 179.31, frame.minY + 61.78), controlPoint1: CGPointMake(frame.minX + 184.62, frame.minY + 61.38), controlPoint2: CGPointMake(frame.minX + 179.31, frame.minY + 61.78))
        bottomHolderPath.addLineToPoint(CGPointMake(frame.minX + 140.69, frame.minY + 61.78))
        bottomHolderPath.addCurveToPoint(CGPointMake(frame.minX + 132.97, frame.minY + 63.38), controlPoint1: CGPointMake(frame.minX + 140.69, frame.minY + 61.78), controlPoint2: CGPointMake(frame.minX + 135.38, frame.minY + 61.38))
        bottomHolderPath.addCurveToPoint(CGPointMake(frame.minX + 131.04, frame.minY + 69.75), controlPoint1: CGPointMake(frame.minX + 130.56, frame.minY + 65.37), controlPoint2: CGPointMake(frame.minX + 131.04, frame.minY + 69.75))
        bottomHolderPath.closePath()
        upperRectangleStrokeColor.setStroke()
        bottomHolderPath.lineWidth = 0.5
        bottomHolderPath.stroke()


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 157, frame.minY + 61, 6, 6))
        UIColor.grayColor().setFill()
        ovalPath.fill()
        UIColor.darkGrayColor().setStroke()
        ovalPath.lineWidth = 0.5
        ovalPath.stroke()


        //// UpperHolder Drawing
        let upperHolderPath = UIBezierPath()
        upperHolderPath.moveToPoint(CGPointMake(frame.minX + 130.04, frame.minY + 70))
        upperHolderPath.addLineToPoint(CGPointMake(frame.minX + 189.96, frame.minY + 70))
        upperHolderPath.addCurveToPoint(CGPointMake(frame.minX + 187.96, frame.minY + 62.03), controlPoint1: CGPointMake(frame.minX + 189.96, frame.minY + 70), controlPoint2: CGPointMake(frame.minX + 190.46, frame.minY + 64.52))
        upperHolderPath.addCurveToPoint(CGPointMake(frame.minX + 179.97, frame.minY + 60.04), controlPoint1: CGPointMake(frame.minX + 185.47, frame.minY + 59.54), controlPoint2: CGPointMake(frame.minX + 179.97, frame.minY + 60.04))
        upperHolderPath.addLineToPoint(CGPointMake(frame.minX + 140.03, frame.minY + 60.04))
        upperHolderPath.addCurveToPoint(CGPointMake(frame.minX + 132.04, frame.minY + 62.03), controlPoint1: CGPointMake(frame.minX + 140.03, frame.minY + 60.04), controlPoint2: CGPointMake(frame.minX + 134.53, frame.minY + 59.54))
        upperHolderPath.addCurveToPoint(CGPointMake(frame.minX + 130.04, frame.minY + 70), controlPoint1: CGPointMake(frame.minX + 129.54, frame.minY + 64.52), controlPoint2: CGPointMake(frame.minX + 130.04, frame.minY + 70))
        upperHolderPath.closePath()
        keyCircleColor.setFill()
        upperHolderPath.fill()
        upperRectangleStrokeColor.setStroke()
        upperHolderPath.lineWidth = 0.5
        upperHolderPath.stroke()


        //// KeyCircle Drawing
        let keyCirclePath = UIBezierPath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 9.71))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 146.8, frame.minY + 13.86), controlPoint1: CGPointMake(frame.minX + 154.92, frame.minY + 9.71), controlPoint2: CGPointMake(frame.minX + 150.45, frame.minY + 11.25))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 137.46, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 141.15, frame.minY + 17.9), controlPoint2: CGPointMake(frame.minX + 137.46, frame.minY + 24.52))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 54.29), controlPoint1: CGPointMake(frame.minX + 137.46, frame.minY + 44.31), controlPoint2: CGPointMake(frame.minX + 147.44, frame.minY + 54.29))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 182.04, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 172.06, frame.minY + 54.29), controlPoint2: CGPointMake(frame.minX + 182.04, frame.minY + 44.31))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 9.71), controlPoint1: CGPointMake(frame.minX + 182.04, frame.minY + 19.69), controlPoint2: CGPointMake(frame.minX + 172.06, frame.minY + 9.71))
        keyCirclePath.closePath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 185.75, frame.minY + 32))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 58), controlPoint1: CGPointMake(frame.minX + 185.75, frame.minY + 46.36), controlPoint2: CGPointMake(frame.minX + 174.11, frame.minY + 58))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 133.75, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 145.39, frame.minY + 58), controlPoint2: CGPointMake(frame.minX + 133.75, frame.minY + 46.36))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 143.89, frame.minY + 11.4), controlPoint1: CGPointMake(frame.minX + 133.75, frame.minY + 23.61), controlPoint2: CGPointMake(frame.minX + 137.72, frame.minY + 16.15))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 159.75, frame.minY + 6), controlPoint1: CGPointMake(frame.minX + 148.28, frame.minY + 8.01), controlPoint2: CGPointMake(frame.minX + 153.78, frame.minY + 6))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 185.75, frame.minY + 32), controlPoint1: CGPointMake(frame.minX + 174.11, frame.minY + 6), controlPoint2: CGPointMake(frame.minX + 185.75, frame.minY + 17.64))
        keyCirclePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, holderShadow.shadowOffset, holderShadow.shadowBlurRadius, (holderShadow.shadowColor as! UIColor).CGColor)
        keyCircleColor.setFill()
        keyCirclePath.fill()
        CGContextRestoreGState(context)

        keyCircleStrokeColor.setStroke()
        keyCirclePath.lineWidth = 0.5
        keyCirclePath.stroke()


        //// ChainRectangle Drawing
        let chainRectanglePath = UIBezierPath()
        chainRectanglePath.moveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 54))
        chainRectanglePath.addLineToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 61))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 64), controlPoint1: CGPointMake(frame.minX + 158.33, frame.minY + 61), controlPoint2: CGPointMake(frame.minX + 157.58, frame.minY + 63.25))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 64), controlPoint1: CGPointMake(frame.minX + 159.08, frame.minY + 64.75), controlPoint2: CGPointMake(frame.minX + 160.58, frame.minY + 64.75))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 61), controlPoint1: CGPointMake(frame.minX + 162.08, frame.minY + 63.25), controlPoint2: CGPointMake(frame.minX + 161.33, frame.minY + 61))
        chainRectanglePath.addLineToPoint(CGPointMake(frame.minX + 161.33, frame.minY + 54))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 160.33, frame.minY + 50), controlPoint1: CGPointMake(frame.minX + 161.33, frame.minY + 54), controlPoint2: CGPointMake(frame.minX + 162.33, frame.minY + 50))
        chainRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 158.33, frame.minY + 54), controlPoint1: CGPointMake(frame.minX + 158.33, frame.minY + 50), controlPoint2: CGPointMake(frame.minX + 158.33, frame.minY + 54))
        chainRectanglePath.closePath()
        UIColor.grayColor().setFill()
        chainRectanglePath.fill()
    }

    //// Generated Images

    public class func imageOfKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            RectangleKeyRing.drawKeyRing(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), image: image, imageVisible: imageVisible)

        let imageOfKeyRing = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfKeyRing
    }

}
