//
//  SquareKeyRing.swift
//  Blagaprint
//
//  Created by Ivan Magda on 19.01.16.
//  Copyright (c) 2016 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SquareKeyRing : NSObject {

    //// Drawing Methods

    public class func drawKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let color = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 0.602)
        let color2 = UIColor(red: 0.916, green: 0.916, blue: 0.916, alpha: 0.800)

        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.lightGrayColor()
        outerShadow.shadowOffset = CGSizeMake(3.1, 3.1)
        outerShadow.shadowBlurRadius = 5

        //// KeyRingGroup
        //// Square Drawing
        let squarePath = UIBezierPath()
        squarePath.moveToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 94.89))
        squarePath.addLineToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 291.11))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 54.45, frame.minY + 308.55), controlPoint1: CGPointMake(frame.minX + 50.09, frame.minY + 291.11), controlPoint2: CGPointMake(frame.minX + 49, frame.minY + 303.1))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 71.9, frame.minY + 312.91), controlPoint1: CGPointMake(frame.minX + 59.9, frame.minY + 314), controlPoint2: CGPointMake(frame.minX + 71.9, frame.minY + 312.91))
        squarePath.addLineToPoint(CGPointMake(frame.minX + 268.19, frame.minY + 312.91))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 284.55, frame.minY + 307.46), controlPoint1: CGPointMake(frame.minX + 268.19, frame.minY + 312.91), controlPoint2: CGPointMake(frame.minX + 279.09, frame.minY + 312.91))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 290, frame.minY + 291.11), controlPoint1: CGPointMake(frame.minX + 290, frame.minY + 302.01), controlPoint2: CGPointMake(frame.minX + 290, frame.minY + 291.11))
        squarePath.addLineToPoint(CGPointMake(frame.minX + 290, frame.minY + 94.89))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 284.55, frame.minY + 77.45), controlPoint1: CGPointMake(frame.minX + 290, frame.minY + 94.89), controlPoint2: CGPointMake(frame.minX + 290, frame.minY + 82.9))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 268.19, frame.minY + 73.09), controlPoint1: CGPointMake(frame.minX + 279.09, frame.minY + 72), controlPoint2: CGPointMake(frame.minX + 268.19, frame.minY + 73.09))
        squarePath.addLineToPoint(CGPointMake(frame.minX + 71.9, frame.minY + 73.09))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 54.45, frame.minY + 77.45), controlPoint1: CGPointMake(frame.minX + 71.9, frame.minY + 73.09), controlPoint2: CGPointMake(frame.minX + 59.9, frame.minY + 72))
        squarePath.addCurveToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 94.89), controlPoint1: CGPointMake(frame.minX + 49, frame.minY + 82.9), controlPoint2: CGPointMake(frame.minX + 50.09, frame.minY + 94.89))
        squarePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        squarePath.fill()
        CGContextRestoreGState(context)

        UIColor.lightGrayColor().setStroke()
        squarePath.lineWidth = 0.5
        squarePath.stroke()


        if (imageVisible) {
            //// SquareWithPhoto Drawing
            let squareWithPhotoRect = CGRectMake(frame.minX + 50, frame.minY + 73, 240, 240)
            let squareWithPhotoPath = UIBezierPath()
            squareWithPhotoPath.moveToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 94.89))
            squareWithPhotoPath.addLineToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 291.11))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 54.45, frame.minY + 308.55), controlPoint1: CGPointMake(frame.minX + 50.09, frame.minY + 291.11), controlPoint2: CGPointMake(frame.minX + 49, frame.minY + 303.1))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 71.9, frame.minY + 312.91), controlPoint1: CGPointMake(frame.minX + 59.9, frame.minY + 314), controlPoint2: CGPointMake(frame.minX + 71.9, frame.minY + 312.91))
            squareWithPhotoPath.addLineToPoint(CGPointMake(frame.minX + 268.19, frame.minY + 312.91))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 284.55, frame.minY + 307.46), controlPoint1: CGPointMake(frame.minX + 268.19, frame.minY + 312.91), controlPoint2: CGPointMake(frame.minX + 279.09, frame.minY + 312.91))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 290, frame.minY + 291.11), controlPoint1: CGPointMake(frame.minX + 290, frame.minY + 302.01), controlPoint2: CGPointMake(frame.minX + 290, frame.minY + 291.11))
            squareWithPhotoPath.addLineToPoint(CGPointMake(frame.minX + 290, frame.minY + 94.89))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 284.55, frame.minY + 77.45), controlPoint1: CGPointMake(frame.minX + 290, frame.minY + 94.89), controlPoint2: CGPointMake(frame.minX + 290, frame.minY + 82.9))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 268.19, frame.minY + 73.09), controlPoint1: CGPointMake(frame.minX + 279.09, frame.minY + 72), controlPoint2: CGPointMake(frame.minX + 268.19, frame.minY + 73.09))
            squareWithPhotoPath.addLineToPoint(CGPointMake(frame.minX + 71.9, frame.minY + 73.09))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 54.45, frame.minY + 77.45), controlPoint1: CGPointMake(frame.minX + 71.9, frame.minY + 73.09), controlPoint2: CGPointMake(frame.minX + 59.9, frame.minY + 72))
            squareWithPhotoPath.addCurveToPoint(CGPointMake(frame.minX + 50.09, frame.minY + 94.89), controlPoint1: CGPointMake(frame.minX + 49, frame.minY + 82.9), controlPoint2: CGPointMake(frame.minX + 50.09, frame.minY + 94.89))
            squareWithPhotoPath.closePath()
            CGContextSaveGState(context)
            CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
            CGContextBeginTransparencyLayer(context, nil)
            CGContextSaveGState(context)
            squareWithPhotoPath.addClip()
            image.drawInRect(CGRectMake(floor(squareWithPhotoRect.minX + 0.5), floor(squareWithPhotoRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
            CGContextEndTransparencyLayer(context)
            CGContextRestoreGState(context)

        }




        //// KeyHolderGroup
        //// Hole Drawing
        let holePath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 64, frame.minY + 81, 28, 28))
        UIColor.darkGrayColor().setFill()
        holePath.fill()


        //// Brace Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 30.25, frame.minY + 61.01)
        CGContextRotateCTM(context, -20 * CGFloat(M_PI) / 180)

        let bracePath = UIBezierPath()
        bracePath.moveToPoint(CGPointMake(13.99, 46.48))
        bracePath.addCurveToPoint(CGPointMake(31.59, 67.83), controlPoint1: CGPointMake(15.03, 63.63), controlPoint2: CGPointMake(19.54, 67.83))
        bracePath.addCurveToPoint(CGPointMake(53.38, 48.4), controlPoint1: CGPointMake(43.64, 67.83), controlPoint2: CGPointMake(54.12, 66.25))
        bracePath.addCurveToPoint(CGPointMake(21.21, 0.84), controlPoint1: CGPointMake(52.65, 30.56), controlPoint2: CGPointMake(21.21, 0.84))
        bracePath.addLineToPoint(CGPointMake(-0, -0))
        bracePath.addCurveToPoint(CGPointMake(13.99, 46.48), controlPoint1: CGPointMake(-0, -0), controlPoint2: CGPointMake(12.94, 29.33))
        bracePath.closePath()
        color2.setFill()
        bracePath.fill()
        UIColor.lightGrayColor().setStroke()
        bracePath.lineWidth = 0.5
        bracePath.stroke()

        CGContextRestoreGState(context)


        //// KeyCircle Drawing
        let keyCirclePath = UIBezierPath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 44, frame.minY + 10.71))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 27.56, frame.minY + 15.98), controlPoint1: CGPointMake(frame.minX + 37.87, frame.minY + 10.71), controlPoint2: CGPointMake(frame.minX + 32.2, frame.minY + 12.66))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 15.71, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 20.39, frame.minY + 21.11), controlPoint2: CGPointMake(frame.minX + 15.71, frame.minY + 29.51))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 67.29), controlPoint1: CGPointMake(frame.minX + 15.71, frame.minY + 54.62), controlPoint2: CGPointMake(frame.minX + 28.38, frame.minY + 67.29))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 72.29, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 59.62, frame.minY + 67.29), controlPoint2: CGPointMake(frame.minX + 72.29, frame.minY + 54.62))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 10.71), controlPoint1: CGPointMake(frame.minX + 72.29, frame.minY + 23.38), controlPoint2: CGPointMake(frame.minX + 59.62, frame.minY + 10.71))
        keyCirclePath.closePath()
        keyCirclePath.moveToPoint(CGPointMake(frame.minX + 77, frame.minY + 39))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 72), controlPoint1: CGPointMake(frame.minX + 77, frame.minY + 57.23), controlPoint2: CGPointMake(frame.minX + 62.23, frame.minY + 72))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 11, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 25.77, frame.minY + 72), controlPoint2: CGPointMake(frame.minX + 11, frame.minY + 57.23))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 23.87, frame.minY + 12.85), controlPoint1: CGPointMake(frame.minX + 11, frame.minY + 28.35), controlPoint2: CGPointMake(frame.minX + 16.04, frame.minY + 18.89))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 6), controlPoint1: CGPointMake(frame.minX + 29.44, frame.minY + 8.56), controlPoint2: CGPointMake(frame.minX + 36.42, frame.minY + 6))
        keyCirclePath.addCurveToPoint(CGPointMake(frame.minX + 77, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 62.23, frame.minY + 6), controlPoint2: CGPointMake(frame.minX + 77, frame.minY + 20.77))
        keyCirclePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        color.setFill()
        keyCirclePath.fill()
        CGContextRestoreGState(context)

        UIColor.grayColor().setStroke()
        keyCirclePath.lineWidth = 0.5
        keyCirclePath.stroke()
    }

    //// Generated Images

    public class func imageOfKeyRing(frame frame: CGRect = CGRectMake(0, 0, 320, 320), image: UIImage = UIImage(named: "image.png")!, imageVisible: Bool = false) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SquareKeyRing.drawKeyRing(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), image: image, imageVisible: imageVisible)

        let imageOfKeyRing = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfKeyRing
    }

}
