//
//  LenovoS850.swift
//  Blagaprint
//
//  Created by Ivan Magda on 31.10.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class LenovoS850 : NSObject {

    //// Cache

    struct Cache {
        static var outerShadow: NSShadow = NSShadow(color: UIColor.darkGrayColor().colorWithAlphaComponent(0.7), offset: CGSizeMake(-6.1, 8.1), blurRadius: 15)
        static var innerShadow: NSShadow = NSShadow(color: UIColor.darkGrayColor(), offset: CGSizeMake(1.1, -2.1), blurRadius: 4)
    }

    //// Initialization

    override class func load() {
    }

    //// Shadows

    class var outerShadow: NSShadow { return Cache.outerShadow }
    class var innerShadow: NSShadow { return Cache.innerShadow }

    //// Drawing Methods

    class func drawLenovoS(frame: CGRect, colorOfText: UIColor, fillColor: UIColor, image: UIImage, textYscale: CGFloat, caseText: String, textRectHeight: CGFloat, textSize: CGFloat, textXscale: CGFloat, backgroundImageVisible: Bool) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let strokeColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.104)
        var fillColorRedComponent: CGFloat = 1,
            fillColorGreenComponent: CGFloat = 1,
            fillColorBlueComponent: CGFloat = 1
        fillColor.getRed(&fillColorRedComponent, green: &fillColorGreenComponent, blue: &fillColorBlueComponent, alpha: nil)

        let caseStrokeColor = UIColor(red: (fillColorRedComponent * 0.9), green: (fillColorGreenComponent * 0.9), blue: (fillColorBlueComponent * 0.9), alpha: (CGColorGetAlpha(fillColor.CGColor) * 0.9 + 0.1))

        //// Shadow Declarations
        let cameraOuterShadow = NSShadow(color: UIColor.grayColor(), offset: CGSizeMake(0.1, 2.1), blurRadius: 3)
        let cameraInnerShadow = NSShadow(color: UIColor.grayColor(), offset: CGSizeMake(0.1, -0.1), blurRadius: 10)

        //// Image Declarations
        let lenovoS850CameraImage = UIImage(contentsOfFile: "lenovoS850CameraImage.png")

        //// Rectangle Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 120.5, frame.minY + 220.5)

        var rectanglePath = UIBezierPath()
        rectanglePath.moveToPoint(CGPointMake(-80, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-105, -173.28), controlPoint1: CGPointMake(-101, -201), controlPoint2: CGPointMake(-105, -173.28))
        rectanglePath.addLineToPoint(CGPointMake(-105, -141.6))
        rectanglePath.addLineToPoint(CGPointMake(-105, 115.8))
        rectanglePath.addLineToPoint(CGPointMake(-105, 155.4))
        rectanglePath.addCurveToPoint(CGPointMake(-80, 195), controlPoint1: CGPointMake(-105, 155.4), controlPoint2: CGPointMake(-105, 195))
        rectanglePath.addCurveToPoint(CGPointMake(-20, 195), controlPoint1: CGPointMake(-28.8, 195), controlPoint2: CGPointMake(-27.38, 195))
        rectanglePath.addCurveToPoint(CGPointMake(40, 195), controlPoint1: CGPointMake(-9.1, 195), controlPoint2: CGPointMake(12.93, 195))
        rectanglePath.addCurveToPoint(CGPointMake(80, 195), controlPoint1: CGPointMake(48.24, 195), controlPoint2: CGPointMake(38.53, 195))
        rectanglePath.addCurveToPoint(CGPointMake(105, 155.4), controlPoint1: CGPointMake(102, 195), controlPoint2: CGPointMake(105, 155.4))
        rectanglePath.addLineToPoint(CGPointMake(105, 115.8))
        rectanglePath.addCurveToPoint(CGPointMake(105, -141.6), controlPoint1: CGPointMake(105, 115.8), controlPoint2: CGPointMake(105, -128.87))
        rectanglePath.addCurveToPoint(CGPointMake(105, -173.28), controlPoint1: CGPointMake(105, -142.36), controlPoint2: CGPointMake(105, -173.28))
        rectanglePath.addCurveToPoint(CGPointMake(80, -201), controlPoint1: CGPointMake(105, -173.28), controlPoint2: CGPointMake(101, -201))
        rectanglePath.addCurveToPoint(CGPointMake(40, -201), controlPoint1: CGPointMake(64.66, -201), controlPoint2: CGPointMake(44.96, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-20, -201), controlPoint1: CGPointMake(27.23, -201), controlPoint2: CGPointMake(-15.54, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-80, -201), controlPoint1: CGPointMake(-27.69, -201), controlPoint2: CGPointMake(-30.3, -201))
        rectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, LenovoS850.outerShadow.shadowOffset, LenovoS850.outerShadow.shadowBlurRadius, LenovoS850.outerShadow.shadowColor.CGColor)
        fillColor.setFill()
        rectanglePath.fill()

        ////// Rectangle Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, rectanglePath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha(LenovoS850.innerShadow.shadowColor.CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let rectangleOpaqueShadow = LenovoS850.innerShadow.shadowColor.colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, LenovoS850.innerShadow.shadowOffset, LenovoS850.innerShadow.shadowBlurRadius, rectangleOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, kCGBlendModeSourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        rectangleOpaqueShadow.setFill()
        rectanglePath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        CGContextRestoreGState(context)

        strokeColor.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()

        CGContextRestoreGState(context)


        if (backgroundImageVisible) {
            //// Background Image Rectangle Drawing
            CGContextSaveGState(context)
            CGContextTranslateCTM(context, frame.minX + 120.5, frame.minY + 220.5)

            let backgroundImageRectangleRect: CGRect = CGRectMake(-105, -201, 210, 396)
            var backgroundImageRectanglePath = UIBezierPath()
            backgroundImageRectanglePath.moveToPoint(CGPointMake(-80, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-105, -173.28), controlPoint1: CGPointMake(-101, -201), controlPoint2: CGPointMake(-105, -173.28))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, -141.6))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, 115.8))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, 155.4))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-80, 195), controlPoint1: CGPointMake(-105, 155.4), controlPoint2: CGPointMake(-105, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-20, 195), controlPoint1: CGPointMake(-28.8, 195), controlPoint2: CGPointMake(-27.38, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(40, 195), controlPoint1: CGPointMake(-9.1, 195), controlPoint2: CGPointMake(12.93, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(80, 195), controlPoint1: CGPointMake(48.24, 195), controlPoint2: CGPointMake(38.53, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, 155.4), controlPoint1: CGPointMake(102, 195), controlPoint2: CGPointMake(105, 155.4))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(105, 115.8))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, -141.6), controlPoint1: CGPointMake(105, 115.8), controlPoint2: CGPointMake(105, -128.87))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, -173.28), controlPoint1: CGPointMake(105, -142.36), controlPoint2: CGPointMake(105, -173.28))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(80, -201), controlPoint1: CGPointMake(105, -173.28), controlPoint2: CGPointMake(101, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(40, -201), controlPoint1: CGPointMake(64.66, -201), controlPoint2: CGPointMake(44.96, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-20, -201), controlPoint1: CGPointMake(27.23, -201), controlPoint2: CGPointMake(-15.54, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-80, -201), controlPoint1: CGPointMake(-27.69, -201), controlPoint2: CGPointMake(-30.3, -201))
            backgroundImageRectanglePath.closePath()
            CGContextSaveGState(context)
            CGContextSetShadowWithColor(context, LenovoS850.outerShadow.shadowOffset, LenovoS850.outerShadow.shadowBlurRadius, LenovoS850.outerShadow.shadowColor.CGColor)
            CGContextBeginTransparencyLayer(context, nil)
            CGContextSaveGState(context)
            backgroundImageRectanglePath.addClip()
            image.drawInRect(CGRectMake(floor(backgroundImageRectangleRect.minX + 0.5), floor(backgroundImageRectangleRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
            CGContextEndTransparencyLayer(context)

            ////// Background Image Rectangle Inner Shadow
            CGContextSaveGState(context)
            CGContextClipToRect(context, backgroundImageRectanglePath.bounds)
            CGContextSetShadow(context, CGSizeMake(0, 0), 0)
            CGContextSetAlpha(context, CGColorGetAlpha(LenovoS850.innerShadow.shadowColor.CGColor))
            CGContextBeginTransparencyLayer(context, nil)
            let backgroundImageRectangleOpaqueShadow = LenovoS850.innerShadow.shadowColor.colorWithAlphaComponent(1)
            CGContextSetShadowWithColor(context, LenovoS850.innerShadow.shadowOffset, LenovoS850.innerShadow.shadowBlurRadius, backgroundImageRectangleOpaqueShadow.CGColor)
            CGContextSetBlendMode(context, kCGBlendModeSourceOut)
            CGContextBeginTransparencyLayer(context, nil)

            backgroundImageRectangleOpaqueShadow.setFill()
            backgroundImageRectanglePath.fill()

            CGContextEndTransparencyLayer(context)
            CGContextEndTransparencyLayer(context)
            CGContextRestoreGState(context)

            CGContextRestoreGState(context)

            strokeColor.setStroke()
            backgroundImageRectanglePath.lineWidth = 1
            backgroundImageRectanglePath.stroke()

            CGContextRestoreGState(context)
        }


        //// Text Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 16, frame.minY + 100)
        CGContextRotateCTM(context, 90 * M_PI / 180)
        CGContextScaleCTM(context, textXscale, textYscale)

        let textRect: CGRect = CGRectMake(0, -93.33, 280, (textRectHeight + 10.0033333333))
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Left;

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "AndersonSupercar", size: textSize), NSForegroundColorAttributeName: colorOfText, NSParagraphStyleAttributeName: textStyle]

        NSString(string: caseText).drawInRect(CGRectOffset(textRect, 0, (textRect.height - NSString(string: caseText).boundingRectWithSize(textRect.size, options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height) / 2), withAttributes: textFontAttributes);

        CGContextRestoreGState(context)


        //// Camera Drawing
        let cameraRect: CGRect = CGRectMake(frame.minX + 37, frame.minY + 32, 35, 60)
        var cameraPath = UIBezierPath()
        cameraPath.moveToPoint(CGPointMake(frame.minX + 72, frame.maxY - 358.02))
        cameraPath.addCurveToPoint(CGPointMake(frame.maxX - 168, frame.maxY - 396.42), controlPoint1: CGPointMake(frame.minX + 72, frame.maxY - 371.92), controlPoint2: CGPointMake(frame.maxX - 168, frame.maxY - 380.44))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 54.54, frame.minY + 32), controlPoint1: CGPointMake(frame.maxX - 168, frame.maxY - 404.39), controlPoint2: CGPointMake(frame.minX + 63.28, frame.minY + 31.88))
        cameraPath.addCurveToPoint(CGPointMake(frame.maxX - 203, frame.minY + 43.58), controlPoint1: CGPointMake(frame.minX + 45.78, frame.minY + 32.13), controlPoint2: CGPointMake(frame.maxX - 203, frame.minY + 36.12))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 37, frame.minY + 81.98), controlPoint1: CGPointMake(frame.maxX - 203, frame.minY + 58.48), controlPoint2: CGPointMake(frame.minX + 37, frame.minY + 69.17))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 72, frame.maxY - 358.02), controlPoint1: CGPointMake(frame.minX + 37, frame.minY + 94.79), controlPoint2: CGPointMake(frame.minX + 72, frame.maxY - 344.12))
        cameraPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, cameraOuterShadow.shadowOffset, cameraOuterShadow.shadowBlurRadius, cameraOuterShadow.shadowColor.CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        cameraPath.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(cameraRect.minX, -cameraRect.minY, lenovoS850CameraImage.size.width, lenovoS850CameraImage.size.height), lenovoS850CameraImage.CGImage)
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)

        ////// Camera Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, cameraPath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha(cameraInnerShadow.shadowColor.CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let cameraOpaqueShadow = cameraInnerShadow.shadowColor.colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, cameraInnerShadow.shadowOffset, cameraInnerShadow.shadowBlurRadius, cameraOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, kCGBlendModeSourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        cameraOpaqueShadow.setFill()
        cameraPath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        CGContextRestoreGState(context)

        caseStrokeColor.setStroke()
        cameraPath.lineWidth = 1.5
        cameraPath.stroke()
    }

    //// Generated Images

    class func imageOfLenovoS(frame: CGRect, colorOfText: UIColor, fillColor: UIColor, image: UIImage, textYscale: CGFloat, caseText: String, textRectHeight: CGFloat, textSize: CGFloat, textXscale: CGFloat, backgroundImageVisible: Bool) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(320, 568), false, 0)
        LenovoS850.drawLenovoS(frame, colorOfText: colorOfText, fillColor: fillColor, image: image, textYscale: textYscale, caseText: caseText, textRectHeight: textRectHeight, textSize: textSize, textXscale: textXscale, backgroundImageVisible: backgroundImageVisible)
        var imageOfLenovoS = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfLenovoS!
    }

}



extension NSShadow {
    convenience init(color: AnyObject!, offset: CGSize, blurRadius: CGFloat) {
        self.init()
        self.shadowColor = color
        self.shadowOffset = offset
        self.shadowBlurRadius = blurRadius
    }
}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
