//
//  XperiaZ1.swift
//  Blagaprint
//
//  Created by Ivan Magda on 31.10.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class XperiaZ1 : NSObject {

    //// Cache

    struct Cache {
        static var outerShadow: NSShadow = NSShadow(color: UIColor.darkGrayColor().colorWithAlphaComponent(0.7), offset: CGSizeMake(-6.1, 8.1), blurRadius: 15)
        static var innerShadow: NSShadow = NSShadow(color: UIColor.darkGrayColor(), offset: CGSizeMake(1.1, -2.1), blurRadius: 4)
    }

    //// Initialization

    override class func load() {
    }

    //// Shadows

    class var outerShadow: NSShadow { return Cache.outerShadow }
    class var innerShadow: NSShadow { return Cache.innerShadow }

    //// Drawing Methods

    class func drawXperiaZ(frame: CGRect, colorOfText: UIColor, fillColor: UIColor, image: UIImage, textYscale: CGFloat, caseText: String, textSize: CGFloat, textXscale: CGFloat, backgroundImageVisible: Bool, textRectHeight: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let strokeColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.104)
        var fillColorRedComponent: CGFloat = 1,
            fillColorGreenComponent: CGFloat = 1,
            fillColorBlueComponent: CGFloat = 1
        fillColor.getRed(&fillColorRedComponent, green: &fillColorGreenComponent, blue: &fillColorBlueComponent, alpha: nil)

        let cameraStrokeColor = UIColor(red: (fillColorRedComponent * 0.75), green: (fillColorGreenComponent * 0.75), blue: (fillColorBlueComponent * 0.75), alpha: (CGColorGetAlpha(fillColor.CGColor) * 0.75 + 0.25))

        //// Shadow Declarations
        let cameraOuterShadow = NSShadow(color: UIColor.grayColor(), offset: CGSizeMake(0.1, 2.1), blurRadius: 3)
        let cameraInnerShadow = NSShadow(color: UIColor.grayColor(), offset: CGSizeMake(0.1, -0.1), blurRadius: 10)

        //// Image Declarations
        let xperiaZ1CameraImage = UIImage(contentsOfFile: "xperiaZ1CameraImage.png")

        //// Rectangle Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 120.5, frame.minY + 220.5)

        var rectanglePath = UIBezierPath()
        rectanglePath.moveToPoint(CGPointMake(-80, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-105, -173.28), controlPoint1: CGPointMake(-101, -201), controlPoint2: CGPointMake(-105, -173.28))
        rectanglePath.addLineToPoint(CGPointMake(-105, -141.6))
        rectanglePath.addLineToPoint(CGPointMake(-105, 115.8))
        rectanglePath.addLineToPoint(CGPointMake(-105, 155.4))
        rectanglePath.addCurveToPoint(CGPointMake(-80, 195), controlPoint1: CGPointMake(-105, 155.4), controlPoint2: CGPointMake(-105, 195))
        rectanglePath.addCurveToPoint(CGPointMake(-20, 195), controlPoint1: CGPointMake(-28.8, 195), controlPoint2: CGPointMake(-27.38, 195))
        rectanglePath.addCurveToPoint(CGPointMake(40, 195), controlPoint1: CGPointMake(-9.1, 195), controlPoint2: CGPointMake(12.93, 195))
        rectanglePath.addCurveToPoint(CGPointMake(80, 195), controlPoint1: CGPointMake(48.24, 195), controlPoint2: CGPointMake(38.53, 195))
        rectanglePath.addCurveToPoint(CGPointMake(105, 155.4), controlPoint1: CGPointMake(102, 195), controlPoint2: CGPointMake(105, 155.4))
        rectanglePath.addLineToPoint(CGPointMake(105, 115.8))
        rectanglePath.addCurveToPoint(CGPointMake(105, -141.6), controlPoint1: CGPointMake(105, 115.8), controlPoint2: CGPointMake(105, -128.87))
        rectanglePath.addCurveToPoint(CGPointMake(105, -173.28), controlPoint1: CGPointMake(105, -142.36), controlPoint2: CGPointMake(105, -173.28))
        rectanglePath.addCurveToPoint(CGPointMake(80, -201), controlPoint1: CGPointMake(105, -173.28), controlPoint2: CGPointMake(101, -201))
        rectanglePath.addCurveToPoint(CGPointMake(40, -201), controlPoint1: CGPointMake(64.66, -201), controlPoint2: CGPointMake(44.96, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-20, -201), controlPoint1: CGPointMake(27.23, -201), controlPoint2: CGPointMake(-15.54, -201))
        rectanglePath.addCurveToPoint(CGPointMake(-80, -201), controlPoint1: CGPointMake(-27.69, -201), controlPoint2: CGPointMake(-30.3, -201))
        rectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, XperiaZ1.outerShadow.shadowOffset, XperiaZ1.outerShadow.shadowBlurRadius, XperiaZ1.outerShadow.shadowColor.CGColor)
        fillColor.setFill()
        rectanglePath.fill()

        ////// Rectangle Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, rectanglePath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha(XperiaZ1.innerShadow.shadowColor.CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let rectangleOpaqueShadow = XperiaZ1.innerShadow.shadowColor.colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, XperiaZ1.innerShadow.shadowOffset, XperiaZ1.innerShadow.shadowBlurRadius, rectangleOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, kCGBlendModeSourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        rectangleOpaqueShadow.setFill()
        rectanglePath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        CGContextRestoreGState(context)

        strokeColor.setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()

        CGContextRestoreGState(context)


        if (backgroundImageVisible) {
            //// Background Image Rectangle Drawing
            CGContextSaveGState(context)
            CGContextTranslateCTM(context, frame.minX + 120.5, frame.minY + 220.5)

            let backgroundImageRectangleRect: CGRect = CGRectMake(-105, -201, 210, 396)
            var backgroundImageRectanglePath = UIBezierPath()
            backgroundImageRectanglePath.moveToPoint(CGPointMake(-80, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-105, -173.28), controlPoint1: CGPointMake(-101, -201), controlPoint2: CGPointMake(-105, -173.28))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, -141.6))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, 115.8))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(-105, 155.4))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-80, 195), controlPoint1: CGPointMake(-105, 155.4), controlPoint2: CGPointMake(-105, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-20, 195), controlPoint1: CGPointMake(-28.8, 195), controlPoint2: CGPointMake(-27.38, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(40, 195), controlPoint1: CGPointMake(-9.1, 195), controlPoint2: CGPointMake(12.93, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(80, 195), controlPoint1: CGPointMake(48.24, 195), controlPoint2: CGPointMake(38.53, 195))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, 155.4), controlPoint1: CGPointMake(102, 195), controlPoint2: CGPointMake(105, 155.4))
            backgroundImageRectanglePath.addLineToPoint(CGPointMake(105, 115.8))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, -141.6), controlPoint1: CGPointMake(105, 115.8), controlPoint2: CGPointMake(105, -128.87))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(105, -173.28), controlPoint1: CGPointMake(105, -142.36), controlPoint2: CGPointMake(105, -173.28))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(80, -201), controlPoint1: CGPointMake(105, -173.28), controlPoint2: CGPointMake(101, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(40, -201), controlPoint1: CGPointMake(64.66, -201), controlPoint2: CGPointMake(44.96, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-20, -201), controlPoint1: CGPointMake(27.23, -201), controlPoint2: CGPointMake(-15.54, -201))
            backgroundImageRectanglePath.addCurveToPoint(CGPointMake(-80, -201), controlPoint1: CGPointMake(-27.69, -201), controlPoint2: CGPointMake(-30.3, -201))
            backgroundImageRectanglePath.closePath()
            CGContextSaveGState(context)
            CGContextSetShadowWithColor(context, XperiaZ1.outerShadow.shadowOffset, XperiaZ1.outerShadow.shadowBlurRadius, XperiaZ1.outerShadow.shadowColor.CGColor)
            CGContextBeginTransparencyLayer(context, nil)
            CGContextSaveGState(context)
            backgroundImageRectanglePath.addClip()
            image.drawInRect(CGRectMake(floor(backgroundImageRectangleRect.minX + 0.5), floor(backgroundImageRectangleRect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
            CGContextEndTransparencyLayer(context)

            ////// Background Image Rectangle Inner Shadow
            CGContextSaveGState(context)
            CGContextClipToRect(context, backgroundImageRectanglePath.bounds)
            CGContextSetShadow(context, CGSizeMake(0, 0), 0)
            CGContextSetAlpha(context, CGColorGetAlpha(XperiaZ1.innerShadow.shadowColor.CGColor))
            CGContextBeginTransparencyLayer(context, nil)
            let backgroundImageRectangleOpaqueShadow = XperiaZ1.innerShadow.shadowColor.colorWithAlphaComponent(1)
            CGContextSetShadowWithColor(context, XperiaZ1.innerShadow.shadowOffset, XperiaZ1.innerShadow.shadowBlurRadius, backgroundImageRectangleOpaqueShadow.CGColor)
            CGContextSetBlendMode(context, kCGBlendModeSourceOut)
            CGContextBeginTransparencyLayer(context, nil)

            backgroundImageRectangleOpaqueShadow.setFill()
            backgroundImageRectanglePath.fill()

            CGContextEndTransparencyLayer(context)
            CGContextEndTransparencyLayer(context)
            CGContextRestoreGState(context)

            CGContextRestoreGState(context)

            strokeColor.setStroke()
            backgroundImageRectanglePath.lineWidth = 1
            backgroundImageRectanglePath.stroke()

            CGContextRestoreGState(context)
        }


        //// Text Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 16, frame.minY + 100)
        CGContextRotateCTM(context, 90 * M_PI / 180)
        CGContextScaleCTM(context, textXscale, textYscale)

        let textRect: CGRect = CGRectMake(0, -93.33, 280, (textRectHeight + 10.0033333333))
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Left;

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "AndersonSupercar", size: textSize), NSForegroundColorAttributeName: colorOfText, NSParagraphStyleAttributeName: textStyle]

        NSString(string: caseText).drawInRect(CGRectOffset(textRect, 0, (textRect.height - NSString(string: caseText).boundingRectWithSize(textRect.size, options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height) / 2), withAttributes: textFontAttributes);

        CGContextRestoreGState(context)


        //// Camera Drawing
        let cameraRect: CGRect = CGRectMake(frame.minX + 40, frame.minY + 40, 40, 56)
        var cameraPath = UIBezierPath()
        cameraPath.moveToPoint(CGPointMake(frame.minX + 75.31, frame.minY + 45.11))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 74.05, frame.minY + 76.17), controlPoint1: CGPointMake(frame.minX + 83.29, frame.minY + 51.5), controlPoint2: CGPointMake(frame.minX + 79.88, frame.minY + 70.03))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 73.93, frame.minY + 78.72), controlPoint1: CGPointMake(frame.minX + 74.02, frame.minY + 77.03), controlPoint2: CGPointMake(frame.minX + 73.98, frame.minY + 77.89))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 73.93, frame.minY + 88.77), controlPoint1: CGPointMake(frame.minX + 73.7, frame.minY + 82.72), controlPoint2: CGPointMake(frame.minX + 73.93, frame.minY + 86.22))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 46.75, frame.minY + 88.77), controlPoint1: CGPointMake(frame.minX + 73.93, frame.minY + 97.99), controlPoint2: CGPointMake(frame.minX + 46.75, frame.minY + 98.82))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 46.75, frame.minY + 78.72), controlPoint1: CGPointMake(frame.minX + 46.75, frame.minY + 86.25), controlPoint2: CGPointMake(frame.minX + 47.07, frame.minY + 82.27))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 46.63, frame.minY + 77.12), controlPoint1: CGPointMake(frame.minX + 46.71, frame.minY + 78.2), controlPoint2: CGPointMake(frame.minX + 46.67, frame.minY + 77.66))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 44.45, frame.minY + 45.11), controlPoint1: CGPointMake(frame.minX + 41.24, frame.minY + 72.26), controlPoint2: CGPointMake(frame.minX + 35.99, frame.minY + 51.88))
        cameraPath.addCurveToPoint(CGPointMake(frame.minX + 75.31, frame.minY + 45.11), controlPoint1: CGPointMake(frame.minX + 52.97, frame.minY + 38.3), controlPoint2: CGPointMake(frame.minX + 66.78, frame.minY + 38.3))
        cameraPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, cameraOuterShadow.shadowOffset, cameraOuterShadow.shadowBlurRadius, cameraOuterShadow.shadowColor.CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        cameraPath.addClip()
        CGContextScaleCTM(context, 1, -1)
        CGContextDrawTiledImage(context, CGRectMake(cameraRect.minX, -cameraRect.minY, xperiaZ1CameraImage.size.width, xperiaZ1CameraImage.size.height), xperiaZ1CameraImage.CGImage)
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)

        ////// Camera Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, cameraPath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha(cameraInnerShadow.shadowColor.CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let cameraOpaqueShadow = cameraInnerShadow.shadowColor.colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, cameraInnerShadow.shadowOffset, cameraInnerShadow.shadowBlurRadius, cameraOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, kCGBlendModeSourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        cameraOpaqueShadow.setFill()
        cameraPath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        CGContextRestoreGState(context)

        cameraStrokeColor.setStroke()
        cameraPath.lineWidth = 1
        cameraPath.stroke()
    }

    //// Generated Images

    class func imageOfXperiaZ(frame: CGRect, colorOfText: UIColor, fillColor: UIColor, image: UIImage, textYscale: CGFloat, caseText: String, textSize: CGFloat, textXscale: CGFloat, backgroundImageVisible: Bool, textRectHeight: CGFloat) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(320, 568), false, 0)
        XperiaZ1.drawXperiaZ(frame, colorOfText: colorOfText, fillColor: fillColor, image: image, textYscale: textYscale, caseText: caseText, textSize: textSize, textXscale: textXscale, backgroundImageVisible: backgroundImageVisible, textRectHeight: textRectHeight)
        var imageOfXperiaZ = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfXperiaZ!
    }

}



extension NSShadow {
    convenience init(color: AnyObject!, offset: CGSize, blurRadius: CGFloat) {
        self.init()
        self.shadowColor = color
        self.shadowOffset = offset
        self.shadowBlurRadius = blurRadius
    }
}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
